### ISSUE TITLE
voiceUri value isn't sent to cboard-api when the user change Language

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard#1007]
When logged user changes language. The default voice is not updated on user settings Data (database)

**Comment by martinbedouret** [comment]
@tomivm I am not sure if we have to save the voice uri into the db. The voice uri depends on the device / browser you load the application. So if you save it for example using chrome and then you open the app in Firefox, the voice uri will not be there. The voice uri looks as a local parameter to me, we have to store it in the redux state, but not in the database.
