### ISSUE TITLE
Implement a custom header for all API response messages 

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#1016]
@sylvansson I was thinking of implementing a custom header in all of the API responses to be used by the front-end app. A use case for this header would be the PR https://github.com/cboard-org/cboard/pull/1014 in order to redirect to the login page JUST in case of the 403 error comes from the API. I'm open to any suggestion from you.

**Comment by sylvansson** [comment]
That would definitely be an option, although if we only want to identify 403s returned by the Cboard API from an Axios interceptor, then we should be able to simply compare `error.request.host` to `BASE_URL`.

**Comment by martinbedouret** [comment]
you are right, fixed using the following update `error.config.baseURL === BASE_URL`
