### ISSUE TITLE
text on Live feature is not properly aligned.

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard#1051]
![imagen](https://user-images.githubusercontent.com/21298844/137420777-c8be1d36-a50a-487e-a9b8-549f31dd03f1.png)
this cause more issues if the scroll bar is necessary
![imagen](https://user-images.githubusercontent.com/21298844/137420887-41d93a58-3bfb-4d74-aac7-016fa6276d37.png)

**Comment by RodriSanchez1** [comment]
![image](https://user-images.githubusercontent.com/80465873/137495062-ad179634-3aea-4a4d-9a6a-9bafa51a8ea8.png)

in google chrome
