### ISSUE TITLE
White screen when going to language settings in Chrome, Edge and Firefox

### ISSUE THREAD

**Issue by eadraffan** [cboard-org/cboard#1055]
When selecting language settings to change the language a white screen appears. https://app.cboard.io/settings/language.  I am using Windows 10, Chrome, Edge and Firefox in English.  Other settings appear to work normally, but with the language setting it does not reload the setting page when you try to go back.  You have to return to the home board.

**Comment by eadraffan** [comment]
On the Android app the language settings work, but the information sheet about more languages has lost all the images.

**Comment by martinbedouret** [comment]
This was due to an update on Microsoft text to speech voices. We have already fixed it.
