### ISSUE TITLE
Some times the  navigation buttons complicates normal use of the board

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard#1065]
Depending on the orientation of the screen and size of UI the Big Button used to navigate between folders is positioned over of buttons or tiles.
see an example:
![Captura de pantalla 2021-11-12 a las 11 52 36](https://user-images.githubusercontent.com/21298844/141486373-3d13aa92-2b4d-4614-bf97-66b5bb10ab85.png)
>
We should Crain a solution for this. 
see an example:
![imagen](https://user-images.githubusercontent.com/21298844/141488726-b9f735b0-96be-45f3-9020-9d9f99262da2.png)

**Comment by RodriSanchez1** [comment]
Also the scroll buttons 
![image](https://user-images.githubusercontent.com/80465873/204593002-c6fbbccb-6c00-4d1e-8403-93f0bdbc36da.png)
