### ISSUE TITLE
Dark Theme support

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#112]
We want to support themes (dark theme for example).

We will need to create `dark` and `white` themes using `ThemeProvider` (already implemented using `material-ui`)
We will need to create a UI toggle to switch between dark/white themes at the settings screen.
Settings screen will need an "Appearance" settings page, and in there a toggle to switch.
Tip: Check how the other pages in the settings folder are built.

**Comment by shayc** [comment]
I'm taking this!

**Comment by martinbedouret** [comment]
below some captures:

![image](https://user-images.githubusercontent.com/8397930/78183898-0393c900-743f-11ea-8dc2-d28eccc44f12.png)

![image](https://user-images.githubusercontent.com/8397930/78184005-3211a400-743f-11ea-821f-11491d7d9093.png)

![image](https://user-images.githubusercontent.com/8397930/78184101-540b2680-743f-11ea-9922-a4b6353847f0.png)

![image](https://user-images.githubusercontent.com/8397930/78184249-8ae13c80-743f-11ea-8c54-d9771129e3b5.png)

![image](https://user-images.githubusercontent.com/8397930/78184414-dc89c700-743f-11ea-842e-1c4f0788dd45.png)
