### ISSUE TITLE
Export fixed board with PicseePal dimension

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard#1126]
Picseepal is a  low-tech visual communication system. This is a new feture which brings the possibilitty to export a fixed board with the Picseepal dimension.

Size of the page: Letter (81/2 × 11 pulgadas) | 279,4 mm × 216 mm
Dimension of the PicseeSnap : 199.39 mm x 132.588 mm
For best result , leave a 1/4 inch (6.35 mm) border of empty space between the edge of the board image and the inner most border of the PicseeSnap
For more information; https://docs.google.com/presentation/d/16MStzDuSiAChZ2Yjn5qPLowpXGxbg99dNPbywhcX1v0/edit#slide=id.ge3ef8c81d3_0_8

![image](https://user-images.githubusercontent.com/80465873/149837622-f0dd430c-8088-494e-8e06-0b51147db67f.png)

Expected result:

![WhatsApp Image 2021-08-26 at 9 39 45 AM](https://user-images.githubusercontent.com/8397930/186510050-c76c95ea-d578-44f1-8475-2175671f76e6.jpeg)

**Comment by eadraffan** [comment]
Picseepal is such a good way of having boards available when technology cannot be used.  I love their templates but we have the same problem with getting the dimensions correct on our PDF export!!   This one could be a useful feature

**Comment by dh-verma** [comment]
I would like to claim this issue please. I am currently in the process of implementing this feature.

**Comment by RodriSanchez1** [comment]
Awesome @dh-verma ! Let me know if you have some doubts!

**Comment by dh-verma** [comment]
Hi @RodriSanchez1 , I have implemented this feature in pull request #1302. I provided some comments in the pull request as well. Would appreciate your feedback, thanks!
