### ISSUE TITLE
Create VoiceRecorder component

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#114]
Create a `VoiceRecorder` "dumb" component to record voice from the users' microphone using Media Capture API.

Implementation should have a microphone icon button (`material-ui`), when clicked, uses the browser recording API, the recorded blob should then be bubbled up through props.

**Comment by shayc** [comment]
taking!

**Comment by NataliaGon** [comment]
I am going to do this component

**Comment by martinbedouret** [comment]
I assume this is going to be per-pictogram , so users can add voice when a board is in edit mode, like following:

![image](https://user-images.githubusercontent.com/8397930/43083907-f1536a2e-8e6d-11e8-925b-fad0661558a3.png)

**Comment by SteveALee** [comment]
This sounds really useful to AlwaysInMind too so I'm watching. Happy to help test etc.

**Comment by shayc** [comment]
Checking the PR, will have a detailed comment soon..
