### ISSUE TITLE
Create SelectedCounter component

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#117]
Create a `SelectedCounter` component, will be used to count selected board buttons when selecting/deselecting buttons on the main page.
Will be placed inside `EditToolbar`.

For example: when 2 buttons are selected it will output "2 buttons selected"
Text should optionally come from props (will have a default value of "items selected")
No need to worry about singular/plurals at this stage.

**Comment by hoodwink73** [comment]
I am taking this up.

@shayc To avoid confusion you can assign this to me

**Comment by hoodwink73** [comment]
@shayc I am taking [Google Inbox's](https://www.dropbox.com/s/fcrkb8mn0ksd43y/Kapture%202017-12-01%20at%2019.12.40.gif?dl=0) selected item as a visual cue. Let me know if we want something else.

**Comment by shayc** [comment]
@hoodwink73 just wanted to know if you're still working on this

**Comment by shayc** [comment]
@hoodwink73 Google Inbox is perfect example

**Comment by hoodwink73** [comment]
@shayc I will raise the PR in a couple of days.
