### ISSUE TITLE
Implement redux-undo

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#118]
When the user edit tiles (delete, edit) he may want to undo his actions.
An Undo button will be shown in the notification bar (bottom), after each delete, edit action.

The bar is already showing when the user deletes tiles:
![image](https://user-images.githubusercontent.com/6969966/55805143-7c8b6980-5ae6-11e9-99a6-944d068f7d17.png)

1) Need to add a button for `undo` action in the notification bar, the `undo` button should only be added when deleting or editing buttons.
2) Need to use `redux-undo` package to implement
3) Need to show notification bar when editing tiles (currently only shows when deleting)
4) With `redux-undo` it's important to only store `past` state for properties that we may want to undo. For performance reasons.

**Comment by shayc** [comment]
Taken by Tamir

**Comment by gavinhenderson** [comment]
Hey @shayc is this issue still taken? 

CC @ktamir

**Comment by martinbedouret** [comment]
@gavinhenderson  thanks! You are assigned to this now.
We will @shayc to verify & review.

**Comment by martinbedouret** [comment]
@gavinhenderson I also added you as a project collaborator with write access to this repository, many thanks for your work!

**Comment by gavinhenderson** [comment]
@martinbedouret Perfect! Will get working on it :)

Now that I am a collaborator is it okay to work on a branch on this repo? Or do you still prefer if I work on a fork?

**Comment by martinbedouret** [comment]
Better if you could work on a branch as it simple for deployment

**Comment by martinbedouret** [comment]
Close due to inactivity
