### ISSUE TITLE
Proptypes error in console when going to settings page

### ISSUE THREAD

**Issue by ktamir** [cboard-org/cboard#123]
index.js:2177 Warning: Failed prop type: Property `langs` of component `LanguageContainer` has invalid PropType notation inside arrayOf.
    in LanguageContainer (created by Connect(LanguageContainer))
    in Connect(LanguageContainer) (at Settings.component.js:105)
    in div (created by Paper)
    in Paper (created by withStyles(Paper))
    in withStyles(Paper) (at FullScreenDialog.js:134)
    in div (at FullScreenDialog.js:133)
    in div (created by Paper)
    in Paper (created by withStyles(Paper))
    in withStyles(Paper) (created by Dialog)
    in Transition (created by Slide)
    in EventListener (created by Slide)
    in Slide (created by withTheme(Slide))
    in withTheme(Slide) (at FullScreenDialog.js:63)
    in TransitionUp (created by Dialog)
    in div (created by Modal)
    in Portal (created by Modal)
    in Modal (created by withStyles(Modal))
    in withStyles(Modal) (created by Dialog)
    in Dialog (created by withStyles(Dialog))
    in withStyles(Dialog) (at FullScreenDialog.js:91)
    in FullScreenDialog (created by withStyles(FullScreenDialog))
    in withStyles(FullScreenDialog) (at Settings.component.js:56)
    in Settings (at Settings.container.js:87)
    in SettingsContainer (created by Connect(SettingsContainer))
    in Connect(SettingsContainer) (at Board.component.js:328)
    in div (at Board.component.js:265)
    in Board (created by InjectIntl(Board))
    in InjectIntl(Board) (at Board.container.js:123)
    in BoardContainer (created by Connect(BoardContainer))
    in Connect(BoardContainer) (at App.js:52)
    in div (at App.js:48)
    in App (created by InjectIntl(App))
    in InjectIntl(App) (created by Connect(InjectIntl(App)))
    in Connect(InjectIntl(App)) (at index.js:21)
    in IntlProvider (at LanguageProvider.container.js:83)
    in LanguageProvider (created by Connect(LanguageProvider))
    in Connect(LanguageProvider) (at index.js:20)
    in SpeechProvider (created by Connect(SpeechProvider))
    in Connect(SpeechProvider) (at index.js:19)
    in PersistGate (at index.js:18)
    in Provider (at index.js:17)

**Comment by shayc** [comment]
thanks, fixed!
