### ISSUE TITLE
Implement trial expired if user was created > 30 days ago 

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#1260]
If the user was created > 30 days ago , the following dialog must be displayed when the board is unlocked: 

![trial](https://user-images.githubusercontent.com/8397930/190934180-bffb51ba-a148-4d09-8e34-f231a26ed6d8.png)

The user creation date can be obtained from the _id property of the user object, see here:  https://www.mongodb.com/docs/manual/reference/method/ObjectId.getTimestamp/

**Comment by dh-verma** [comment]
Hi, I would like to claim this issue
