### ISSUE TITLE
Scroll top on back action

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard#1277]
When a previous board is requried the board view needs to be scrolled to the top position.

Actions that allows to get a previous board:

- Back button navbar
- Browser back action
- ToRootBoard on context aware back butttons
- RequestToPreviousBoard on context aware back buttons

**Comment by akuangkkk** [comment]
Hi, we would like to claim this bug.

**Comment by jayfangjz** [comment]
Me and @akuangkkk  will work on this issue as a team

**Comment by RodriSanchez1** [comment]
Hi!! @akuangkkk  and @jayfangjz  ! I already worked on this issue! I´m waiting to merge a previos pull request to publish the new PR. We can find another issue for you both!
