### ISSUE TITLE
arabic language 

### ISSUE THREAD

**Issue by RAbdalhalim** [cboard-org/cboard#129]
I installed project but didn't it have arabic language in list. how can add it?

**Comment by shayc** [comment]
Hi @RAbdalhalim and welcome!
Arabic is included in Cboard by default but is only available on Apple devices: iPhone, iPad, Mac.
You can use the app here: https://shayc.github.io/cboard
You should be able to change the language in the settings panel (click the lock icon on black bar)

<img src="https://i.imgur.com/sPBX0l9.png" />

**Comment by shayc** [comment]
Closing this issue, please let me know if you any more problems!
