### ISSUE TITLE
Crodwin Translation Badge in Readme

### ISSUE THREAD

**Issue by hoodwink73** [cboard-org/cboard#132]
Hey @shayc 

I was setting up Crowdin for a private project. Came across this status image thing. It might inform people more readily about translation efforts needed.

 
<img width="689" alt="screenshot 2017-12-13 11 58 29" src="https://user-images.githubusercontent.com/1285699/33924678-2a47ae46-dffd-11e7-938a-d06e1130eb7d.png">

---------

<img width="1252" alt="screenshot 2017-12-13 11 53 47" src="https://user-images.githubusercontent.com/1285699/33924679-2bc432c6-dffd-11e7-8063-ba13a0a27afe.png">

**Comment by shayc** [comment]
done! thanks for the screenshot!
