### ISSUE TITLE
Capture the premium features

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard#1351]
Use the `PremiumFeature.js` component to capture all the premium features. Remeber just do it for Android devices. 

List of Premium Features:
- Online NeuralVoices
- Copy public boards
- PublishBoards
- CopyTiles
- Paste tiles
- Usage Analytics',
- Share boards
- Ads Free
- Export to open board format
- SharePhrases
- Private support channel
- Voice recording for tiles

**Comment by tomivm** [comment]
**Ads Free** and **Private support channel** would be captured on a different issue #1352

**Comment by RodriSanchez1** [comment]
- For share board we can do same than the share button on nav bar. That show the share modal, and when you try to share, the feature blocked modal shows up.
- When a online language is selected, a online voice is seted. This avoid the premium modal and breaks the functionality of the blocked feature. I think we can separate the managment of the online voices in other PR
