### ISSUE TITLE
Toggle password visibility

### ISSUE THREAD

**Issue by cirosurf** [cboard-org/cboard#1354]
On log in section add a button that hide and show the password. Its helpful for the users to know what they are writing. Here is an example: 

![maxresdefault](https://user-images.githubusercontent.com/118694534/218558003-32a0fe20-2746-4816-8e72-d44a48b082d5.jpeg)

**Comment by RodriSanchez1** [comment]
Thanks for this idea! I just assigned the issue to you! Thank you! And welcome to Cboard project!

**Comment by shayc** [comment]
There's an example in Material UI v4 docs: https://v4.mui.com/components/text-fields/#input-adornments

**Comment by aarjun8060** [comment]
would you assign to me ?

**Comment by RodriSanchez1** [comment]
@aarjun8060  Yess!

**Comment by agusaar** [comment]
Hi there, is this issue solved? If not, I would like to work on it.
