### ISSUE TITLE
Implement a function that check if user is in a subscription-free country

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard#1355]
Actually, users from determined countries will need a Subscription to access premium features.
2 options could determine this.
1) Use our own location state.
  One impediment to this option is the cases where users' location is not recognized.
  We need to create a scenario for this or bring those users out of the requirement
2) Use Playstore product availability.
  We can check the availability of the products and in cases that any product is available, execute the requirement.
  One impediment to this option is an absence of internet connection or a connection failure that finishes in an empty product list.

**Comment by tomivm** [comment]
Keeping in mind the behavior of 'getting products' explained on #1357 would be better to start using our own location state to determine if a user is in a subscription-free country.

**Comment by RodriSanchez1** [comment]
I was wrong, i just test this behavior of the app offline. The plugin saves the products internaly. The products are loaded no matters if you are offlline
