### ISSUE TITLE
In the case that user cancels subscription from play store, cboard can be used for free until restart or refreshing subscription setting 

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#1404]
In the case that user cancels the subscription from play store, cboard will not know that the user has canceled until restart. We should add a mechanism to update the frontend when user cancels subscription. An intuitive way would be to ask the API the subscription status prior a premium feature is clicked. The drawback to this approach is that we will introduce a big delay on the features as they have to wait for API response. Other approach would be to make the API request asynchronously to the feature action, so if user cancels, the first premium action will always work but second one won't. Any suggestions?

**Comment by RodriSanchez1** [comment]
_When a user cancels a subscription they retain access to the content until the end of the current billing cycle. When the billing cycle ends, access is revoked_. See [Sell subscriptions](https://developer.android.com/google/play/billing/subscriptions#cancel) If he enter on the Subscribe section, will see a cancel status and the date when will expire his premium acces.
