### ISSUE TITLE
"TypeError: CSS2Properties doesn't have an indexed property setter for '0'" raised on homepage in Firefox 57

### ISSUE THREAD

**Issue by toolness** [cboard-org/cboard#145]
On Firefox 57.0.4 on Windows, after running `npm install` and then `npm start`, I'm taken to the locally-hosted app but the following traceback is shown, preventing the app from starting up.

<details>
  <summary>Full traceback<br></summary>
<pre>
TypeError: CSS2Properties doesn't have an indexed property setter for '0'
supported-property.js:73
The above error occurred in the <WithStyles(IconButton)> component:
    in WithStyles(IconButton) (at SymbolOutput.js:125)
    in div (at SymbolOutput.js:108)
    in SymbolOutput (created by WithStyles(SymbolOutput))
    in WithStyles(SymbolOutput) (at Board.component.js:298)
    in div (at Board.component.js:292)
    in Board (created by InjectIntl(Board))
    in InjectIntl(Board) (at Board.container.js:139)
    in BoardContainer (created by Connect(BoardContainer))
    in Connect(BoardContainer) (at App.js:52)
    in div (at App.js:48)
    in App (created by InjectIntl(App))
    in InjectIntl(App) (created by Connect(InjectIntl(App)))
    in Connect(InjectIntl(App)) (at index.js:20)
    in IntlProvider (at LanguageProvider.container.js:92)
    in LanguageProvider (created by Connect(LanguageProvider))
    in Connect(LanguageProvider) (at index.js:19)
    in SpeechProvider (created by Connect(SpeechProvider))
    in Connect(SpeechProvider) (at index.js:18)
    in PersistGate (at index.js:17)
    in Provider (at index.js:16)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
index.js:2177
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the LanguageProvider component.
index.js:2177
</pre>
</details>
<br>
I tried visiting the same page with Chrome and Edge and it works fine, though. The page is blank on IE11 but I didn't expect it to work anyways, as I assume IE11 doesn't even support the text-to-speech API required to make this app useful.

**Comment by toolness** [comment]
Er, I guess it's not actually shown in the traceback I copy-pasted from the console, but on the webpage it shows the full path to the files in the traceback, and it looks like the error is coming from the `css-vendor` package, which is being called by `jss`, which is being called by `material-ui`, which is being called by `react-dom`, which is being called by `cboard/src/components/LanguageProvider/LanguageProvider.container.js:74`.  (Actually, I'm not sure if the error logged to the console and the one shown on the webpage are even referring to the same error, which is odd.)

Oh, and I'm using Node v8.4.0.

**Comment by shayc** [comment]
@toolness thanks for letting us know, I just upgraded material-ui (we're using the beta) can you update your fork and try again? You're right, the app isn't supposed to work on IE11. We officially support Firefox/Chrome/Edge/Safari - Please let me know if the problem persists, thanks again!

**Comment by shayc** [comment]
by the way, here's the changelog for the new [`material-ui@1.0.0-beta.29`](https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.29):

> The JSS issues have been fixed

**Comment by shayc** [comment]
Closing, let me know if it persists.

**Comment by toolness** [comment]
Awesome, thanks for the quick fix @shayc !
