### ISSUE TITLE
Exactly where the symbol images came from, if they didn't come from the database?

### ISSUE THREAD

**Issue by rakibul-wdp** [cboard-org/cboard#1562]
I want to know where the symbol images came from. It's in the Symbol.js file and all of the images render by this 
```
{src && (
        <div className="Symbol__image-container">
          <img className="Symbol__image" src={src} alt="" />
        </div>
      )}
```

And I got images in else if condition. So, I need to know the exact image path, so that I can edit or add new images symbol.

```
useEffect(
    () => {
      async function getSrc() {
        let image = null;
        if (keyPath) {
          const arasaacDB = await getArasaacDB();
          image = await arasaacDB.getImageById(keyPath);
        }

        if (image) {
          const blob = new Blob([image.data], { type: image.type });
          setSrc(URL.createObjectURL(blob));
        } else if (props.image) {
          // Cordova path cannot be absolute
          const image =
            isCordova() && props.image && props.image.search('/') === 0
              ? `.${props.image}`
              : props.image;

          console.log('main image=>', image); // I got all of symbol images path from here.

          setSrc(image);
        }
      }

      getSrc();
    },
    [keyPath, setSrc, props.image]
  );
```

**Comment by rakibul-wdp** [comment]
Is it from ```SymbolSearch.component.js``` file and how can I edit any image or symbols?

**Comment by RodriSanchez1** [comment]
Hi @rakibul-wdp How are you? Sorry for the late response. 
The pictogrames that we use are from Arasaac, Mulberry and Global Symbols. On the `SymbolSearch.component.js` , the function getSuggestions() gets the differents pictograms depending on the bank of images. 
If you want to add a custom image, needs to use the button Upload Image on the `TileEditor.component.`. 
The pictograms and the custom images are saved in the prop image of the Tiles objects


Give me more info about wath do you want to do, and i can explain more.
