### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#157]
Create a [Docker ](https://www.docker.com/)container for the app

**Comment by locnguyen** [comment]
If no one has taken this I can do it. I think my only question is why cboard needs a container if it's not a server app.

**Comment by shayc** [comment]
@martinbedouret and @zachi are currently developing the server side, you can see in the app's high-level [roadmap](https://github.com/cboard-org/cboard/blob/master/roadmap.md), and the [cboard-api](https://github.com/cboard-org/cboard-api) repo.

**Comment by amberleyromo** [comment]
@shayc closed with #166?
