### ISSUE TITLE
Add font size selector on PDF export

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard#1575]
A new combo box will be added for select different font size. If not change, default value will be used

**Comment by chelsouse** [comment]
Hello.
I would love to work on this issue. Can you assign it to me please?

**Comment by RodriSanchez1** [comment]
Hi @chelsouse !! Thanks for that! I will asing it  right now! Let me know if you have some doubts!!

**Comment by RodriSanchez1** [comment]
Hi @chelsouse ! How is that going? Do you need any help? Feel free to contact me on Discord. My  id is `.rodrisanchez`

**Comment by erickNjuki** [comment]
Hi @RodriSanchez1 if this issue has not been worked on ,I would love to work on it

**Comment by chelsouse** [comment]
Hello. I am sorry for being quite for some time. I have worked on this task, and it is mostly done, but I need to finalize it. May I have time until monday please? 

I was busy because of school that's why I didn't put any update. I am sorry.

**Comment by ElenaExposito** [comment]
Hello @RodriSanchez1! Is this issue still open? I would love to work on it
