### ISSUE TITLE
Compile RHVOICE for Android 

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#1577]
Follow the instructions for the Android compilation: 
https://github.com/qkqsb/RHVoice/blob/master/doc/en/Compiling-for-Android.md

**Comment by RodriSanchez1** [comment]
You can find the forked repository on [cboardMacedonianPlugin](https://github.com/RodriSanchez1/RHVoice/tree/cboardMacedonianPlugin)
