### ISSUE TITLE
Testing - increasing code coverage

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#158]
We want to increase code coverage to 100%, at the moment we're below 20%, I would start with presentational components first, as these are simple to test and would mostly not change.

- [ ] `About`
- [ ] `ColorSelection`
- [ ] `FormItems`
- [ ] `FullScreenDialog`
- [ ] `Grid`
- [ ] `InputImage`
- [ ] `LoadingIcon`
- [ ] `Notifications`
- [ ] `SelectedCounter`
- [ ] `Settings` (sub components)
- [ ] `SymbolSearch`
- [ ] `WelcomeScreen`

**Comment by johanzilber** [comment]
Working on:
- snapshot testing framework
- snapshot test for ```About``` component

**Comment by johanzilber** [comment]
test for: 
```ColorSelection```
```FormItems```

https://github.com/cboard-org/cboard/pull/163

**Comment by chiptus** [comment]
I think this would be a place to comment, that Select snapshot test is failing. Some space character...
![image](https://user-images.githubusercontent.com/1381655/37211340-455515e8-23b4-11e8-8d5d-8ffbd72cf58f.png)

**Comment by chiptus** [comment]
Can I work on this? e.g on the Loading Icon?

**Comment by johanzilber** [comment]
Snapshot test will fail every time the component was changed. If this was intentional change and not a bug you should override the old snapshot by the new updated one.

**Comment by chiptus** [comment]
It wasn't, I didn't touch `Select`, it's just what I got when I pulled the repo

**Comment by shayc** [comment]
not relevant
