### ISSUE TITLE
Add loading spinner on upload image

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard#1614]
Add a new loading spinner on `TileEditor.component` . It will be displayed when the image is loading. 
Use [progress MUI v4](https://v4.mui.com/components/progress/#progress)

![image](https://github.com/cboard-org/cboard/assets/80465873/fedb99e6-34bc-45d8-b9d5-10775dc1c52c)

**Comment by Davidthecode** [comment]
hey @RodriSanchez1 i could work on this.

**Comment by RodriSanchez1** [comment]
@Davidthecode Hi david! Okayy! You can work on that!

**Comment by Davidthecode** [comment]
hey @RodriSanchez1  where should i add the spinner

**Comment by rakeshkumar1019** [comment]
Hi @RodriSanchez1 raised a PR with solution.
https://github.com/cboard-org/cboard/pull/1622

**Comment by Bhumika2101** [comment]
Heyy @RodriSanchez1
Is this issue solved. If no then I would like to work on it.

**Comment by martinbedouret** [comment]
thanks @Bhumika2101 , but this was already merged and closed.
