### ISSUE TITLE
Prevent enable the 'Improve Phrase' feature when user is not logged 

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard#1627]
Show an alert for unlogged users in free countries trying to enable the Improve Phrase feature.
Also disabled it on Logout. 
Could be possible to only show A message requiring the login on the Space for messages of the feature

**Comment by maxicapodacqua** [comment]
Hi, I'd like to work on this, I might need some guidance on expected behaviors.
I found the feature:
![image](https://github.com/cboard-org/cboard/assets/56036762/3dd73076-d0c6-447e-8d34-06d82a77ffdf)

* Should the alert appear when they try to activate that feature? or after they click Save?
* Any examples of a dialog that requires the user to login?

**Comment by tomivm** [comment]
Hi! Thanks :) Yes. The alert should appear when they try to activate that feature. Also, it should disable it automatically when the user logs out. This is the first feature that requires the user to log in. You could use a similar UI to PremiumRequiered Dialog. Use Material UI v4 Components :) 
You could chat with me on Discord @tomivm 
Thanks for your help
