### ISSUE TITLE
Create the UI to show the user that's not possible to find a pictogram

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard#1650]
Create the UI to show the user that's not possible to find a pictogram for the searched word. Also, it's possible to invite the user to use our Pictonizer (new product) showing a coming soon.
<img width="1280" alt="image" src="https://github.com/cboard-org/cboard/assets/21298844/9648da10-c93b-4bb5-8296-d97eaa7e7e30">

**Comment by maxicapodacqua** [comment]
Hi @tomivm , can you assign this to me? I can start working on it tomorrow

**Comment by maxicapodacqua** [comment]
Is it okay to use MUI Alert element for this?

![image](https://github.com/cboard-org/cboard/assets/56036762/c7ebb6fe-9774-4803-a08e-43847aded997)

Any recommendations for the Pictonizer sentence? do we have to add a link as well?

**Comment by tomivm** [comment]
It looks good if not We could add an icon like
![image](https://github.com/cboard-org/cboard/assets/21298844/c4160ba6-a8b5-47bd-b833-a0b3be201bac)
and use the typography component to write the message.  also, add a disabled button for the Pictonizer indicating that the feature is not available but is coming soon. We could add this later in a different PR. depending on your preferences
