### ISSUE TITLE
UX feedback from behavior therapist

### ISSUE THREAD

**Issue by locnguyen** [cboard-org/cboard#167]
My wife is an ABA behavior therapist and she had some feedback to share:

* Users with autism respond better to real pictures instead of illustrations
* Parents should be able to customize the images
* Parents should be able to order the categories and images by what they think is most important
* The folder was really hard to identify as a folder at first glance

**Comment by shayc** [comment]
This is great input, thanks a lot!

**Comment by hanzhaogang** [comment]
Though closed, I think customing images(adding and replacing) is a really important function.  I suggest that this issue should be considered more seriouslly. @shayc
