### ISSUE TITLE
Root board updated just on local state

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard#1690]
The root board is only updated in the local state. This occurs when the user makes a modification to a subfolder and the user's root board is not saved in the database. The issue appears when the user logs in on another device or will appear if we fix issue #1689.

How to solve it: 
Create the user root board on the db when a subfolder is modified

**Comment by tomivm** [comment]
Also if a local board is modified the folder tiles of other boards that are pointing to the modified board are updated only on the local state. 
You can reproduce this on the "Universal Core 11X6" board. 
1. Make an edition on the home board. 
2. Navigate to people board
3. Click on the home Tile. 
All works as expected 
Now open a new browser and logging with the same account 

1. Navigate to the People folder.
2. Press the Home folder
Now you are in a default home board without your changes
