### ISSUE TITLE
Add security step before delete user account 

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard#1699]
When a user wants to delete their account, after pressing the delete account button, a confirmation modal is displayed without any security measures. This lack of security can lead to unintentional deletions, such as a child accidentally accessing and deleting the account, resulting in the loss of all the user's data.

To prevent this, implementing a security step before deletion is essential. I suggest asking the user to write a confirmation word, similar to the method used by Mongo Compass.

The word can be: cboard, delete, delete-account, or any that the dev want. 

![image](https://github.com/cboard-org/cboard/assets/80465873/79ec3cea-8817-4a27-9455-ededd08e6d57)

**Comment by anmol-fzr** [comment]
Hi 👋, I Would like to work on this issue. Please assign me this one.

**Comment by RodriSanchez1** [comment]
Hello @anmol-fzr! Welcome to the cboard project! We already had @nmro184 working on this issue. I forgot to assign it. You can take #1702 if you want. Leave me a comment there and I'll assign it to you.

**Comment by RodriSanchez1** [comment]
@nmro184 Please leave a comment on this issue. I can not find you on the assign list

**Comment by nmro184** [comment]
Hey , thank you
