### ISSUE TITLE
Fix Default loadBoard for the "Categories" tile on the "Keyboard" Core Board

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard#1704]
The ID used on the loadBoard for the "Categories" tile folder on the "Keyboard" Core Board is wrong. 
https://github.com/tomivm/cboard/blob/d9943f82c3da4bb7e45f9c821588bebfe0b1569e/src/api/corePicSeePal.json#L802

**Comment by kartikeysharma98281** [comment]
hi @tomivm 

can you assign me this issue? and can you please elaborate the issue.

**Comment by tomivm** [comment]
Hi @kartikeysharma98281 only you have to replace the indicated loadBoard ID with the correct ID for the categories board. If you have doubts check the other boards on the JSON file.

**Comment by kartikeysharma98281** [comment]
Please check my PR I fix the wrong id bug inn loadboard.
