### ISSUE TITLE
Quiet mode incorrectly shows activation state in settings

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard#1752]
[See](https://github.com/cboard-org/cboard/blob/1d891598bf9aa247049ab9d606f311fc12f5fda3/src/components/Settings/Navigation/Navigation.component.js#L296)

Change `checked={this.state.enableQuietBuilderMode}` to `checked={this.state.quietBuilderMode}`

**Comment by kkkkYoungJae** [comment]
Can I work on this issue? kindly assign it to me!

**Comment by RodriSanchez1** [comment]
Sure! @kkkkYoungJae
