### ISSUE TITLE
Eye Gaze Communication

### ISSUE THREAD

**Issue by joshraker** [cboard-org/cboard#1757]
In the "Screen scroll through big buttons" section of the user help there is mention of using eye tracking devices. However, I've been unable to find a way to trigger buttons by hovering (dwelling) on them for a set period of time. Am I missing the settings or is this expected to be handled by the eye tracking software?

I'm hacking together an eye-gaze communicator for my daughter until we can get her on medicaid and the most I've been able to get it to do is move the cursor to where I'm looking and she doesn't have the faculties to trigger a button beyond staring at it.

If no such feature exists, I'll try to put up a PR soon. I had started on my own web-based solution before I found Cboard so it shouldn't be too hard to add.

**Comment by tomivm** [comment]
Hello @joshraker . We don't have that feature. if you can implement it and make it optional in the settings that would be awesome!

**Comment by martinbedouret** [comment]
whenever you are able @joshraker Would be great! I'm closing this for now.
