### ISSUE TITLE
Unable to start application on Android device

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#1773]
Many users with complex communication needs are left without their communication system (Cboard) from around 3 days ago because the aplication won't start.
After installing the application on Samsung Galaxy S20 (Android 12) today, the application shows loading screen for a long time (attached as screenshot here)
![Screenshot_20241108-120326_AAC Cboard](https://github.com/user-attachments/assets/471082e9-2f4e-42a9-879a-50b7497a9f57)
, and in some cases the system shows message of an application error (attached as screenshot here).
![Application_error_AAC Cboard](https://github.com/user-attachments/assets/c43c4b09-8271-498c-94c8-905e1686987a)

**Comment by martinbedouret** [comment]
Thank you very much @mzilak .The issue was fixed and an update was published on the Google play store. Closing this.
