### ISSUE TITLE
Two tiles are added to the output bar when selecting in Scanning Mode

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard#1774]
If the output bar is empty and a tile is selected, the tile is added twice to the output.

![image](https://github.com/user-attachments/assets/7e5bfef7-3f82-48c9-8598-2672e06caa00)

**Comment by DTProductions** [comment]
Hello! Is someone working on this issue already? I'd be glad to help and work on it if not.

**Comment by RodriSanchez1** [comment]
Hello @DTProductions, and welcome to the Cboard project! That task is currently unassigned, so feel free to take it on. We're excited to have you onboard!

**Comment by DTProductions** [comment]
Thanks @RodriSanchez1!
