### ISSUE TITLE
Support multiple grid sizes

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#18]
Enhance grid capabilities to support multiple grid sizes.

<Grid rows="3" columns="3">
</Grid>

Need to enable users to change grid size on demand, changing grid size should re-calculate symbols layouts.

Need to implement UI to change grid rows and columns, can be two input fields for rows/columns if a wysiwyg interface proves too difficult.

**Comment by martinbedouret** [comment]
This was done
