### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#19]
Create an icon for Cboard!

**Comment by jquintozamora** [comment]
Do you like that one?
![image](https://user-images.githubusercontent.com/12530031/29683869-cd666dda-8907-11e7-93ec-77a9154a0a88.png)

**Comment by shayc** [comment]
Hi, I prefer a more simple design, I had a look at some of the icons on my mobile phone and they all look very simple, also I'll have to consult Martin before approving anything, if you want you can prepare something and I'll make sure that Martin will see it, thanks!
<img src="http://i.imgur.com/6PcmqeZ.png">

**Comment by hoodwink73** [comment]
Hello friends

I think people working on this can take a bit of a help from nounproject.com
Even if we choose to use something from there, we only have to spend very little money

**Comment by shayc** [comment]
thanks, checking..

**Comment by amberleyromo** [comment]
@shayc What about something like this? Simple design, drawing from sign like @jquintozamora initial suggestion, "C" sign art from nounproject, as suggested by @hoodwink73.

Creative Commons attribution - Created by Nicky Knicky from Noun Project

![cboard](https://user-images.githubusercontent.com/3461087/29802098-e62350d4-8c38-11e7-91f3-f4a8fa4fb7ca.png)

**Comment by shayc** [comment]
This is a good candidate

**Comment by amberleyromo** [comment]
Ok, lmk

**Comment by martinbedouret** [comment]
![a52e9213-869b-4205-b364-84ec82b16628](https://user-images.githubusercontent.com/8397930/29844183-b1648fd0-8d0e-11e7-8d22-d56aaf811afd.jpg)

**Comment by amberleyromo** [comment]
@martinbedouret do you like that concept better? if so, do you mind if I take a stab at polishing it a bit?

**Comment by shayc** [comment]
I prefer your icon fwiw

**Comment by amberleyromo** [comment]
@martinbedouret I tried -- I don't really see a way that I prefer it, tbh. How do we want to decide this

**Comment by martinbedouret** [comment]
@amberleyromo i would love if you can take the concept i posted and polish. One suggestion: inside of the talk globe use some squares (meaning an icon board) instead of the three dots "..."
