### ISSUE TITLE
Create a welcome screen

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#22]
`WelcomeScreen` component, displays for first time visitors (or when localStorage is purged)
It contains two pages, first page contains a short intro text welcoming the user, second page contains a form to create a profile (all client side - no server for now), should use [material-ui stepper](https://material-ui-1dab0.firebaseapp.com/demos/stepper/#stepper) for page navigation.
UI examples: https://github.com/apl-devs/AppIntro

**Form fields:**
1. name
2. age
3. gender
4. language

The data will be then used to provide a more personalized experience and enable profile switching in the future

For the form fields use [material-ui](https://material-ui-1dab0.firebaseapp.com/)

Update: the `WelcomeScreen` component is ready, what still needs to be done is CSS styling, and connecting with a Redux store to save user profile.
Note: to style typography (font size etc.) use [`Typography`](https://material-ui-1dab0.firebaseapp.com/api/typography/) component

**Comment by shayc** [comment]
This issue is being developed by @erezLieberman

**Comment by amberleyromo** [comment]
Related PR #56

**Comment by shayc** [comment]
Looking for contributor to finish the `WelcomeScreen` component, basically what's left is hooking it up with  the Redux store and CSS styling

**Comment by mcnuttandrew** [comment]
I'd be interested in taking a shot at this!

**Comment by shayc** [comment]
@mcnuttandrew are you still working on this?

**Comment by arthurdenner** [comment]
Is this issue on hold for now? If no, I'd like to work on it, is that OK?

**Comment by mcnuttandrew** [comment]
This kinda got swept under the rug for me, so someone else should feel free to take a crack at it

**Comment by martinbedouret** [comment]
I think is okay to work on this. I am doing good progress on the api rest for the users and we will need the login page soon. Go ahead

**Comment by shayc** [comment]
There's a `WelcomeScreen` component, it's not connected to `Redux` and has no styles.
The welcome screen should look like the general welcome screen on Android apps. If you need examples let me know.

**Comment by arthurdenner** [comment]
Thanks, I'm aware of the `WelcomeScreen` component and already changed some things that were broken, but nothing related to the styles. If you could give some examples, I'd really appreciate it. You can send through Discord if you want, I've joined the server.

**Comment by arthurdenner** [comment]
Taking this issue.
