### ISSUE TITLE
Don't show signup fields after signup request is submitted

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#224]
After clicking on signup button, a message is displayed asking for email confirmation.
At that moment, signup fields should not be displayed anymore, as they are confused to the user.

![screenshot from 2018-04-20 13-06-46](https://user-images.githubusercontent.com/8397930/39062156-0a5a00d4-449d-11e8-9556-6fa6aeb81bf9.png)

**Comment by arthurdenner** [comment]
@shayc, can you close this, since it was implemented in #240?
