### ISSUE TITLE
Enable the change of pitch and rate in speech settings screen

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#23]
Add two new inputs to Settings/Speech screen that will represent pitch and rate.

Pitch and rate values can range between 0 (lowest) and 2 (highest), with 1 being the default pitch/rate for the current platform or voice. 

You should use [material-ui](https://material-ui-1dab0.firebaseapp.com/) for the input fields
A slider component is most suitable for this type of settings but unfortunately material-ui beta 4 doesn't support it, can offer other components.

**Comment by BrendanFDMoore** [comment]
I'd like to take a shot at this one. Is there any WIP on it?

Since the linked MUI doesn't support sliders like you want, and doesn't appear to have steppers either ( :weary: ), how do you feel about an implementation using +/- buttons?

Rough mock up:
<img width="453" alt="online_mockup__wireframe___ui_prototyping_tool_ _moqups" src="https://user-images.githubusercontent.com/4238814/29566967-bf0ba812-8719-11e7-97d7-1bf490677004.png">

**Comment by shayc** [comment]
Currently no WIP, I like your proposal, it's a good compromise.

I was thinking about this:
<img src="http://i.imgur.com/9o6HjCa.png">

No need for save/cancel buttons, when the user change the Pitch/Rate it'll just save, we're using Redux to manage state, I've already mapped some actions like changeRate() and changePitch() in Settings/Speech component (pull latest version), let me know if you have any questions, I am happy to help!

P.S.
Do you think we need to make the changes to Pitch/Rate values in .25 increments? This should be better in terms of UX than just letting users click many several times. 

Helpful links:
https://material-ui-1dab0.firebaseapp.com/demos/lists/
https://material-ui-1dab0.firebaseapp.com/demos/buttons/

**Comment by BrendanFDMoore** [comment]
Yea, when I started poking at it I changed tack a little bit. I've got something in the works that I think you'll like (and I can adjust if you don't :D ).

I found the action creators :+1: so I will certainly be leveraging them.

As for the save/cancel, that was something I considered before seeing your action pipeline. Totally fine to just have it dispatched and stored immediately with an intermediate step. I'll drop those out.

**Comment by BrendanFDMoore** [comment]
Oh, and if needed what is your process for adding new terms to the i18n? I didn't see anything about that in the docs.

**Comment by BrendanFDMoore** [comment]
Here's what I've got pulled together now:
<img width="766" alt="cboard_-_aac_communication_board" src="https://user-images.githubusercontent.com/4238814/29600869-6f4e47b6-87a6-11e7-8cbd-9ba5962e847c.png">

It doesn't currently show the value, but I'm not sure it's a useful number for users anyway.

**Comment by shayc** [comment]
merged, awesome job mate! loving it!
I'll tweak the UI a little in the future (perhaps new icons) but it's not important.
The only thing I'm going to add is a debounced event handler for 300ms so it wont read the sampleSentence each time.. thank you so much!

**Comment by shayc** [comment]
regarding the translation strings we're using crowdin.com as a translation management platform. right now only authorized contributors can add/delete new string there, I am happy to add those strings myself, but if you want, I can give you the permissions.. let me know
