### ISSUE TITLE
Integrate arasaac.org symbol set

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#27]
Integrate with ARASAAC symbols API. ARASAAC provides more than 10k symbols. This feature has huge value to our users.
Need to get a list of all symbols, translate them into 33 languages and create a dictionary. Used whenever a user wants to add/change an image.

ARASAAC:
https://beta.arasaac.org/pictograms/search/
https://github.com/juanda99/arasaac-frontend/blob/master/app/components/Pictogram/index.js

See #90 for UI example

**Comment by martinbedouret** [comment]
This was done
