### ISSUE TITLE
Keyboard navigation with arrow keys

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#29]
Enable navigation between symbols by using the arrow keys

**Comment by ioRekz** [comment]
Is this arrow keys for moving and Enter to speak/go inside category ? 

Also, what is the reasoning behind this feature ?

**Comment by ioRekz** [comment]
I'm not sure what's the best way to get the current layout so we know which item to select when going down or up

**Comment by shayc** [comment]
@ioRekz this is a minor feature in regards to the the MVP milestone, but a complex one to implement since the symbols can be moved and change size. The motivation behind this is to make the app accessible through the keyboard (desktop) and [external switches (iPad)](http://www.hirstwood.com/course-notes/online-ipad-training-2/ipads-with-external-switches/) (some users can't use a mouse/touch easily).

I wouldn't start with this one just yet, not until we'll get access to an external switch. I'll contact manufacturers see if they drop something - will keep you updated.

**Comment by shayc** [comment]
closing, related: #48
