### ISSUE TITLE
there should be a separate translation for cricket - sport and cricket - insect

### ISSUE THREAD

**Issue by evertbouw** [cboard-org/cboard#3]
I am working on the Dutch translations, but I've run into this problem. The Dutch translation for the insect should be _krekel_ but for the sport it's just _cricket_.

**Comment by agupta93** [comment]
@evertbouw thanks for pointing this out will find a solution for this and get back to you.

**Comment by shayc** [comment]
@evertbouw we have an awesome translation service, I didn't know you started working on it already, I'll open an account for you ASAP.

**Comment by shayc** [comment]
solved - thanks!
