### ISSUE TITLE
Export / Import boards, for backup and sharing.

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#30]
Initial version should just be able to output a json file and load it

**Comment by jquintozamora** [comment]
Hi @shayc , 
Fantastic project! I'll give this a go. 
I guess that requires:
  - A new button to export/import in the navigation?
  - Export all items in (Board) . board. symbols  and the id into a JSON

**Comment by shayc** [comment]
The users' boards are stored in our Redux state on the 'boards' property.
Right now the 'boards' property isn't exposed in our Containers/Board file.

So basically:
- Expose the 'boards' Redux state property in Containers/Board file - use the existing mapStateToProps function
- Create a new React componet in Components/ExportButton the components should ([use material-ui](https://material-ui-1dab0.firebaseapp.com/demos/buttons/)) they have a special link button that will generate an html Anchor element with href.
- see example on how to implement JSON download link: https://jsfiddle.net/cowboy/hHZa9/
- Import said ExportButton to Containers/Board and add the component to the black toolbar

Let me know if you need help with anything or have any questions, thank you and welcome aboard 😄

**Comment by jquintozamora** [comment]
Hi @shayc , 
Thank you, I've implemented "Export" functionality. I've used quite different approach for generating the json file, please take a look handleExportClick function to see if that's what you are expecting. 

Thinking about the Import functionality.

Do you prefer a new button for importing?
Should we use IconButton instead of "text" Button?

**Comment by jquintozamora** [comment]
@shayc , Should we check the format of boards' JSON before imports it ?

If so, do you know any specific approach?

**Comment by shayc** [comment]
I've taken a look on npm and found this popular package: [ajv](https://www.npmjs.com/package/ajv)
You can check if you like it. What we need is something to validate the structure and type of the boards JSON file. If you think we should use something else for validation let me know.. I have no experience with ajv, thanks!

**Comment by shayc** [comment]
done by @jquintozamora
