### ISSUE TITLE
Create a startup screen for android/ios (web)

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#31]
https://developers.google.com/web/updates/2015/10/splashscreen

<link rel="apple-touch-startup-image" href="/launch.png">

**Comment by gagyibenedek** [comment]
I'll jump on this!

**Comment by shayc** [comment]
Not much work should be done, base the design based on @amberleyromo #19, prepare a simple splash screen png file in all supported sizes and reference it in the `/public/index.html` file - should support iOS/Android browsers,

**Comment by gagyibenedek** [comment]
Finally got around to work on this. Sadly I realized, that it's 99% photoshop/image manipulation work, for which I don't have the experience. So I'll have to pass it on to the next person. Sorry about that.

**Comment by amberleyromo** [comment]
@shayc What info were you thinking to include? I have the illustrator files, so I can put it together.

**Comment by shayc** [comment]
should be fairly simple: 

option 1. the app icon with the 'cboard' logo and the gradient spanning the entire screen.
option 2. the app icon with the 'cboard' logo and a white background for the entire screen

**Comment by shayc** [comment]
done
