### ISSUE TITLE
Prevent body scroll when dragging symbols

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#32]
on iOS devices, when rearranging symbols the body also scrolls, preventing fluid dragging of symbols.
can try overflow: hidden on body when dragging.. not sure

**Comment by amberleyromo** [comment]
One problem here is there has to be some degree of scrolling, because not all symbols are visible in the viewport.

**Comment by shayc** [comment]
one way we can solve this is by tap & hold for 500ms before a symbol starts to drag, this way quick scrolling gestures will work.

**Comment by HarryGogonis** [comment]
This might be related to this bug in `react-grid-layout` https://github.com/STRML/react-grid-layout/issues/338

I can reproduce this on their [demo page](https://strml.github.io/react-grid-layout/examples/1-basic.html)

**Comment by falinsky** [comment]
@HarryGogonis seems like it's fixed in react-draggable:v3.0.2 which is still not used by react-grid-layout (even in 0.15.0)

**Comment by shayc** [comment]
oh @HarryGogonis @falinsky, I'll contact the author of react-grid-layout, see if he can update or I can make PR. Thanks for the info!

**Comment by shayc** [comment]
by the way, in react-grid-layout 0.14.7 changelog:

> 0.14.7 (Jul 14, 2017)
> 
> Fixed a dragging bug when the grid container is scrollable. Thanks @chultquist.
> Ref: https://github.com/STRML/react-grid-layout/pull/555

I guess we know it wasn't fixed, trying to upgrade to 0.15.

**Comment by shayc** [comment]
Apparently the bug is no longer reproducing on iOS 11
