### ISSUE TITLE
symbol should speak label or text

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#33]
Currently when you click on a symbol it speaks the content of the label property of symbol.
We should make changes so when a text property has a value, that value will get precedence over the label value when using speech synthesis.

The text value was planned specifically to override the label when using speech.

Should look something like this:

```
speakSymbol() {
  const text = symbol.text || symbol.label;
  this.speak(text);
}
```

**Comment by falinsky** [comment]
@shayc will these text properties have translations?

**Comment by shayc** [comment]
Yes they will, right now boards.json doesn't contain any 'text' properties, I will add them pretty soon to crowdin.com (our translation management platform) basically you go ahead with this since if 'text' property is falsey it'll fallback to the 'label' property. Will be glad to help if you have any questions!
