### ISSUE TITLE
Sign Up Verification Email: foxmail.com and qq.com can't receive verification emails

### ISSUE THREAD

**Issue by hanzhaogang** [cboard-org/cboard#337]
I don't know if this is a real issue, but my foxmail.com and qq.com mailbox cann't receive the mail. Both of them are used by many Chinese people. But my gmail.com account can get the mail immediately.

**Comment by shayc** [comment]
is there any chance the confirmation email was sent to `junk`/`spam` folder?

**Comment by hanzhaogang** [comment]
I checked the spam folder but they were not there. Later I will try to register with other email servers like 163.com and check the results.

**Comment by hanzhaogang** [comment]
Confirmed that aliyun.com& 163.com can both receive the verify mail.

**Comment by martinbedouret** [comment]
thank you for this!!

**Comment by martinbedouret** [comment]
I see that qq.com needed a retry, but it was finally delivered 
![image](https://user-images.githubusercontent.com/8397930/48854031-90c90700-ed8f-11e8-8377-c1c3b770059c.png)

**Comment by hanzhaogang** [comment]
@martinbedouret  I tried to register an account with my 1106361@qq.com email(again) last night. And yes, I checked my inbox just now and the verify mail is there.  But a weeks ago(when I open this issue), I tried to sign up with both 1106361@qq.com and hanzhaogang@foxmail.com and could not get the verify mail. They are tried before I signed up with hanzhaogang@gmail.com and received the mail.  

I know this is probably not an issue of cboard but  my mail server, since in China we sometimes complain that we cannot receive some mails with qq.com.  If you have time, could you help to check for the verify mails before my register with hanzhaogang@gmail.com?

**Comment by klues** [comment]
I tried to register with my mail address klaus@technikum-wien.at
However, I've never got a confirmation mail and cannot login on the login page. What can I do?

**Comment by phanducthien82** [comment]
Go to settings, choose anti-spam, choose whitelist, then add github.com and save
