### ISSUE TITLE
Blank page when changing output or board - needs to refresh page

### ISSUE THREAD

**Issue by hanzhaogang** [cboard-org/cboard#338]
Hi, while using the app, for example, I add some icons to the top area to make a communication, and then I want to remove them all, so I click the remove all button(next to the most top right icon), but a white page appeared. After I refresh the page, my remove all action take affect and those icons I want to remove desappered. I don't think it is due to the network connection, bucause I tried to close the network connection, and continue to use the app(since it is a PWA), and this issue can still be reproduced.

Besides this, there are also other actions that need a refresh page action to make them take effects.(For example, if the communication area is emtpy and I am trying add the first icon)  

If I click  the "emotion" directory in the home page(I want to enter that package), after I clicked  a white page shows up again and a refresh page action is required to see the icons in that package. But, the "back" icon on the top left corner of the panel area(which can take me to the home page) is missing for this "emotion" package.

I tried on both safari and chrome in my iphone, and I tried many times.

**Comment by shayc** [comment]
i wasn't able to reproduce, were you trying on a production build `app.cboard.io` or a local build.. are there any errors in the console?

**Comment by hanzhaogang** [comment]
I hit this issue on the production build app.cboard.io. My local build works perfectly without any blank page with my desktop chrome.  I use my phone so I cann't get a console. Maybe it is an issue related with the network connection?

**Comment by martinbedouret** [comment]
@tinchodipalma can you reproduce this?

**Comment by tinchodipalma** [comment]
@hanzhaogang would you mind clearing cache? Maybe in incognito should be enough.

**Comment by hanzhaogang** [comment]
@tibovanheule  I cheared cache and loged out, then the issue is stille there. Both in chrome and safari in my iphone.

**Comment by tinchodipalma** [comment]
I could not reproduce the issue with the xcode iphone simulator

![iphone x - safari - app cboard io 1](https://user-images.githubusercontent.com/6096768/48904702-f673cc80-ee3d-11e8-905d-d1b999987908.gif)

**Comment by hanzhaogang** [comment]
I used a screen recorder, so my finger cann't be seen. In fact each time I got a blank screen, I pressed the refreash icon and everything become normal.  Perhaps the screen recorder has its own browser, but the behavior of the app is the same as in safari and chrome.

There is no problem when I use it in my laptop chrome browser. And my iphone and laptop are using the same wifi.  


iphone 6s plus with ios version 10.2 , default safari, chrome 70.0.3538.75, 

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/3948562/48906546-c8bf6f80-ee9f-11e8-9c04-7272e8bb3ef2.gif)

**Comment by tinchodipalma** [comment]
iOS and Safari versions? Did you try by clearing all web data at the iPhone settings menu?

**Comment by hanzhaogang** [comment]
iOS 10.2（14C92）， Safari 10.0,   WebKitversion 602.3.12 （according to whatismybrowser.com）.  I tried : setting->Safari->clear history record and website data. the issue is still there.

**Comment by tinchodipalma** [comment]
Thanks @hanzhaogang, I could reproduce it with those versions. Would you mind to check if its happening in https://app.qa.cboard.io (I've submitted a fix)? Thank you!

Please clear web data and caché, you might need to refresh the page one or two times.

**Comment by hanzhaogang** [comment]
@tinchodipalma  Thanks!  The issue is gone in [https://app.qa.cboard.io](https://app.qa.cboard.io), for both the safari and the chrome in my iphone.

**Comment by tinchodipalma** [comment]
Thanks for your reply @hanzhaogang 

Can you check the issue again in prod (https://app.cboard.io)? Please remember to clear all web data.

**Comment by hanzhaogang** [comment]
@tinchodipalma I checked and this issue is gone in  prod[ https://app.cboard.io](https://app.cboard.io). I think we can close it now.

**Comment by tinchodipalma** [comment]
https://github.com/cboard-org/cboard/pull/342
