### ISSUE TITLE
App crashes when entering a created folder

### ISSUE THREAD

**Issue by mn113** [cboard-org/cboard#34]
I don't know if this functionality is supposed to exist yet.

**Steps to reproduce:**
1. Start from a fresh dev build (cboard 0.1.0)
2. On the homescreen, click Add button
3. Search for any picture and select it
4. Set the type to Folder
5. Save it
6. Click on the new folder

**Result:**
React error page with
```TypeError: Cannot read property 'symbols' of undefined
Board.render
src/containers/Board/Board.js:212
> 212 |   const symbols = this.generateSymbols(board.symbols, board.id);
```

What's more, the app remains in this errored state until I call localStorage.clear() in my console (I think because `board.activeBoardId` points to an invalid board).

**Expected behaviour:**
You should be able to enter created folders.

**Comment by shayc** [comment]
Thanks will fix asap

**Comment by shayc** [comment]
fixed [commit](https://github.com/shayc/cboard/commit/6c9f41140c99dc2db6478e6c47ac909b39fb64ac)

**Comment by shayc** [comment]
thanks!
