### ISSUE TITLE
Open Board Format

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#35]
Implement [OBF ](http://www.openboardformat.org/) format for boards.json

**Comment by jquintozamora** [comment]
I could look into that one @shayc , 
I guess that's related to export / import functionality. 
But I think we need to change the way in which the boards are stored and accesses from the Store, isn't it?

**Comment by shayc** [comment]
For this issue I'll want to take a look at the OBF spec first, see how it fits our app. Sure we'll need to change stuff in the Redux Store, our layout object is managed by the Grid container while the Board manages raw board data.. OBF spec combines both them and if I'm not mistaken define stuff in pixels while ours is responsive..

**Comment by shayc** [comment]
At the moment I think we should implement OBF spec to the minimum required by our needs, this feature will bring big value to the product. I've already chatted with a fellow dev interested in incorporating Cboard as the frontend view for his App, it will also enable us to load boards from other sources with relative ease, but requires quite some manual work. Do you need help with anything?

**Comment by shayc** [comment]
Ok gonna convert boards.json to a valid OBF file, see how it goes..
```
{
  "format": "open-board-0.1",
  "id": "root",
  "name": "Advanced Board",
  "description_html": "Communication board for advanced users",
  "license": {
    "type": "CC-By",
    "copyright_notice_url": "http://creativecommons.org/licenses/by",
    "source_url": "http://www.example.com/mysource",
    "author_name": "Shay Cojocaru",
    "author_url": "https://github.com/shayc",
    "author_email": "shayc@outlook.com"
  },
  "buttons": [
    {
      "id": "b1",
      "label": "happy",
      "vocalization": "I am happy, yo",
      "image_id": "i11",
      "background_color": "rgb(255, 241, 118)",
    },
    {
      "id": "b2",
      "label": "feelings",
      "image_id": "i11",
      "background_color": "rgb(187, 222, 251)",
      "load_board": {
        "id": "feelings"
      }
    }
  ],
  "images": [
    {
      "id": "i11",
      "content_type": "image/svg+xml",
      "symbol": {
        "set": "mulberry",
        "filename": "happy.svg"
      }
    },
    {
      "id": "i12",
      "content_type": "image/svg+xml",
      "symbol": {
        "set": "mulberry",
        "filename": "feelings.svg"
      }
    }
  ]
}
```

**Comment by shayc** [comment]
pushed a small script to convert our boards to OBF:
now we need to integrate the structure into our application

script: `format-obf.js`
run: `node format-obf`
output file: `./src/api/boards.obf.json`

**Comment by jquintozamora** [comment]
After quick look into that, that´s big change and I've a question about the desired implementation, for example:
- Do you want to edit the board state to be:
```
{
  id: ...
  buttons: [],
  images: []
}
```

or do you prefer keep doing like:
```
{
  id: ...
  symbols: []
}
```
and then do the integration between button and image into single array called symbols?

What could be easier ?

thanks

**Comment by shayc** [comment]
Yeh the board's state needs to be changed which would also require other changes in container components (`variables`, `props` and `strings`) would make more sense to refactor to buttons/images, current symbols implementation mixes concerns..

I've read a little about state [normalization](http://redux.js.org/docs/recipes/reducers/PrerequisiteConcepts.html#normalizing-data), so we'll want to make the items accessible by id's like this:

```
"boards: {
  "root": {
    "id": "root",
    "format": "open-board-0.1",
    "name": "Advanced Board",
    "description_html": "Communication board for advanced users",
    "license": {
      "type": "CC-By",
      "copyright_notice_url": "http://creativecommons.org/licenses/by",
      "source_url": "http://www.example.com/mysource",
      "author_name": "Shay Cojocaru",
      "author_url": "https://github.com/shayc",
      "author_email": "shayc@outlook.com"
    },
    "buttons": {
      "b1": {
        "id": "b1",
        "label": "happy",
        "vocalization": "I am happy, yo",
        "image_id": "i11",
        "background_color": "rgb(255, 241, 118)",
      }
    },
    "images": {
      "i11": {
        "id": "i11",
        "content_type": "image/svg+xml",
        "symbol": {
          "set": "mulberry",
          "filename": "happy.svg"
        }
      }
    }
  }
}
```

which OBF doesn't support (it uses arrays), so we'll need to adapt the data to our new state structure
I'm going to help with the refactor so don't be intimidated, we just need to announce when anyone is working on some part

**Comment by shayc** [comment]
I am thinking about flattening the structure even more and placing "images" on the same hierarchy as boards, this way, multiple boards will share the same image item: [Storing a single definition for a given item](http://redux.js.org/docs/recipes/reducers/PrerequisiteConcepts.html#normalizing-data)
