### ISSUE TITLE
General <Snackbar /> Component

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#37]
Need to create a general (app wide) Snackbar component, to display various app-wide messages.
Should use [material-ui snackbar](https://material-ui-1dab0.firebaseapp.com/demos/snackbars/)

**Comment by hoodwink73** [comment]
Hey, @shayc I am giving this a go. I will try to be thoughtful with the interface. And post it here, shortly. Let me know if you have any specific requirements.

**Comment by shayc** [comment]
Sounds awesome, the Snackbar component should be general, it should use Redux for state and have a 'message': String and 'open': Boolean properties to show/hide the Snackbar.. If you need help with Redux or have any other questions I am happy to help.

You'll need to create:

- Redux reducer
- Redux action creators
- Redux actions
- Container Snackbar that uses [material-ui](https://material-ui-1dab0.firebaseapp.com/demos/snackbars/) snackbar
- Snackbar.propTypes = { open: PropTypes.boolean, message: PropTypes.string }

**Comment by hoodwink73** [comment]
I am on the right path.

I am also thinking of building a simple queue for the notifications.

`<SnackBar />` suggests showing only one notification at a time. I am respecting this guideline. 

So, suppose notification B triggers when notification A is already displayed.
I would wait until notification A gets dismissed or autohidden, after which I will display notification B.

Do you know think this notification queue will be helpful here?

**Comment by shayc** [comment]
Good point, I checked [material design guidelines](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage) - just to see what the spec says:

> Consecutive snackbars
> 
> There is only ever one snackbar displayed. When a second snackbar is triggered while the first is displayed, the first should start the contraction motion downwards before the second one animates upwards.

Your suggestion is on track with the spec, notification queue will be helpful in some scenarios but if it takes too long to implement we can do with a basic Snackbar for now
