### ISSUE TITLE
obz files - missing root 

### ISSUE THREAD

**Issue by willwade** [cboard-org/cboard#382]
Hi all! I'm trying to debug something - I exported a cboard doc - as a obz - and then uploaded it to pasco.. But I got a problem. It turns out that there is no root in the main object -which I *think* it needs as per the openboard spec: https://github.com/AceCentre/pasco/issues/148

**Comment by djsmithdev** [comment]
<img width="412" alt="snip" src="https://user-images.githubusercontent.com/1619305/68985184-afb37b00-07e2-11ea-9f08-d4490fcd5f41.PNG">

This was output in the latest build, does include a root during my tests.  Unable to reproduce.
