### ISSUE TITLE
customize pictures for symbols should be supported

### ISSUE THREAD

**Issue by hanzhaogang** [cboard-org/cboard#391]
Parents should be able to define their own pictures for certain symbols.  This is an essential feature.

**Comment by martinbedouret** [comment]
@h actually parents can create their own pictograms by adding them from the plus button once settings are unblocked. Is this the same thing you are suggesting?

**Comment by hanzhaogang** [comment]
It should be. Seems that app.cboard.io is unreachable for me currently. Will check it later.
