### ISSUE TITLE
Drag and drop 

### ISSUE THREAD

**Issue by vasek123** [cboard-org/cboard#41]
Hi @shayc! cboard looks like a really cool project. While I was playing around with it I figured that it would be great to have the option to reorder the symbols in the Output component after they were already selected using drag and drop. Is anyone working on such feature?

**Comment by shayc** [comment]
Hi @vasek123 and welcome! this is something I never thought about, I'll talk with Martin Bedouret he's the one in-touch with our speech therapist, and we need to consult with her when it comes to new features.
Will get back to you as soon as I have some info, thanks a lot!

**Comment by shayc** [comment]
@martinbedouret is this something our users need?

**Comment by arthurdenner** [comment]
Hi.

Any news about this feature?
Seems like a good one to add, but a professional opinion would be great.

**Comment by vasek123** [comment]
Guys? Is there some news? @shayc @martinbedouret

**Comment by shayc** [comment]
closing, as far as i'm aware there were no requests for this feature from speech therapists and our trials at rehab centers. seems like a nice feature to implement, but i dont think it'll add much value for our usage type
