### ISSUE TITLE
Sign up error

### ISSUE THREAD

**Issue by rad027** [cboard-org/cboard#437]
Im trying to run this project on my ubuntu 18.04 server but after compiling it using npm it loads perfectly except if you are trying to signup.
heres the error
![image](https://user-images.githubusercontent.com/38456291/58144110-bfad3080-7c7f-11e9-94bd-4f539b64a660.png)

**Comment by martinbedouret** [comment]
Thanks for your time checking Cboard.
This is a platform that requires an API server if you want to run everything on your local environment.
If you want to sign up , my suggestion is just to to use the available platform at https://app.cboard.io
