### ISSUE TITLE
Sign up does not work - no verification mail

### ISSUE THREAD

**Issue by klues** [cboard-org/cboard#455]
Maybe this is related to https://github.com/cboard-org/cboard/issues/337 but since it is already closed I am opening this new issue.

I've tried to sign up using my email address klaus@technikum-wien.at but I've never received a confirmation mail (I have no spam folder). If I afterwards try to login I get "wrong email or password".
What can I do?

**Comment by martinbedouret** [comment]
@klues appreciate the feedback!!
I've verified this and for some reason your email server is blocking our dispatch service (sendgrid.com).
See the details 👍 
![image](https://user-images.githubusercontent.com/8397930/61329492-d0979f80-a7f3-11e9-8352-2f6e9d8b1b57.png)

**Comment by martinbedouret** [comment]
@klues good to see you are also working on an open source AAC!
I liked the **AsTeRICS-Grid** project , please consider to talk to me any time you want.

**Comment by klues** [comment]
Thanks for your answer, I now tried with my private @posteo.de address and sign-up worked! No clue why the server of our university rejects the mail.

However If I login in different browsers and edit a grid in one of them, the change is not seen in the other browsers, even after refresh (F5). Do I miss something, or is this a bug or a missing feature?!

**Comment by klues** [comment]
yeah, lets talk about open source AAC - I'll write you an email 👍
