### ISSUE TITLE
Keyboard accessibility

### ISSUE THREAD

**Issue by AlmeroSteyn** [cboard-org/cboard#48]
Became aware of this awesome project from a tweet by Dan Abramov.

Had a look at it today and really awesome effort!!

I found a couple of (what I think could be) easily fixable issues that would improve the keyboard accessibility of the app.

First and foremost is the use of the following style in `Board.css`:

```
.Symbol:focus {
  outline: 0;
}
```

This, of course, removes the focus outline from tiles, making keyboard navigation pretty much impossible. 

Is this something you want to address in the app? If so I want to see if I can get around to setting up a PR to address basic keyboard accessibility.

**Comment by shayc** [comment]
Hi and welcome :) making the app accessible is a top priority, you're invited to make PR with a fix, let me know if you need help!

**Comment by AlmeroSteyn** [comment]
Thank you! A little busy this side on day job things, will get to it as soon as I can.

**Comment by a11yup-old** [comment]
Also became aware through Dan on Twitter. Really cool project. Keep up the good work 👍 

I'd also love to help out with improving keyboard accessibility for the app.
@AlmeroSteyn Let me know if I can help out here ;) I have a little bit of time a the moment.

**Comment by AlmeroSteyn** [comment]
@dakeyras7 Help would be great! Sorry it took so long, wanted to take the time to have an initial opinion, which only happened today. Please comment on the pull request with your ideas.

Opened PR #61

**Comment by shayc** [comment]
I've fixed the styling with the IconButton on focus, I'll have to refactor later to abstract IconButton implementation, probably into another Component or via theme configuration

**Comment by shayc** [comment]
The more I think of the problem the more I'm inclined to have main keyboard navigation be done by arrow keys and backspace/delete keys. Tab navigation should be enabled to traverse all interactive elements but not be used as the main nav method since it is cumbersome. Please be aware that once changing the symbols layout within the app, tab navigation gets messed up (the DOM/taborder doesn't change). So this needs further implementation. For now we have the basics - thank you!

**Comment by AlmeroSteyn** [comment]
@shayc Thanks for merging the PR and picking up the Iconbutton issue!

Maybe some points for consideration on the navigiation method. Users who make use of keyboard navigation, especially those using assistive tech, often have a specific expectation of how this works.

I think `TAB` navigation should remain the main navigation form as this is already expected by these users. Users will not easily expect focus on a `button` element to be moved to the next `button` element using arrow keys, unless this is clear explained. This will mean having to create accessible instructions for screen reader users as they wont even know that the next element exists and would expect `TAB` to discover this element if it is there. The arrow keys are also used by screen readers in their browsing mode to read the page unless we deal with specific WAI-ARIA controls that use them (such as a `tab control`).

That does not mean you cannot add shortcuts to the app to make it even easier for users who want to them but I will recommend that `TAB` navigation remains the default. 

As for the focus issues, yeah this is typical of JavaScript rendered applactions but the focus can be easily restored again on the clicked button in its new location using React `refs` and setting focus on the element.

Skip links can also be added (the a11y only menu you mentioned)  to quickly jump between different sections in the app. 

As for `backspace` I would not recommend remapping this key as users in many browsers are used to this being the key for `navigate back` and will be, I think, super confusing.

What do you think?

**Comment by a11yup-old** [comment]
I was also inclined about that idea @shayc :) but have to agree with @AlmeroSteyn regarding the point about `TAB` vs `arrow` keys.

So I would suggest to work on the next steps to improve things:

* Get the focus to stay on the board 
* Adding skip links to get to the board directly

I'll give them a shot.

**Comment by a11yup-old** [comment]
Feel free to review #65. I decided to do the focus tracking first and left the skip links out for now. I came up with an idea for back-navigation with the `Esc` key which felt alright to me. Opinions welcome!

**Comment by shayc** [comment]
closing this, thanks @dakeyras7, if you think there should be more work done feel free to open a PR
