### ISSUE TITLE
The application often does not remember selected language in the settings

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#511]
Coming back to application after not using the application for some time or closing all recently used applications, the language is set up to Serbian instead of Croatian

**Comment by mzilak** [comment]
Here is an example scenario when this bug occurred:
1. Open the application after installing
2. Change of language from Serbian to Croatian in the settings
3. Creating new board
4. Close the application 
5. Close all recent applications
6. Open the application > the language is Serbian again

**Comment by martinbedouret** [comment]
Fixed. it will be available on 1.0.8
