### ISSUE TITLE
Issues for back navigation

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#543]
1) After clicking the back button when in certain category of symbols (e.g. quick chat), a blank
page occurs.
2) Pressing the back button in every screen of the app (except in settings) doesn't work unless the user presses some symbol. It redirects the user to https://app.cboard.io/board/null page which is blank. Sometimes the issue is not present.
3) Refreshing the page does not help, only solution is to open the page again. This problem did not appear when using Firefox, only when using Chrome.
4) When clicking the back button in the home bar, the user is not properly redirected (backwards to the root board). Sometimes it works, sometimes it takes the user back to certain categories opened before and sometimes to the page ending up with /board/null.

* Steps to reproduce: Click the back button when in some category of symbols/when on some screen of the application. Sometimes the failure occurs when button „Go Back One Page“ in web browser is clicked and sometime when application button „Go Back“ is clicked.
One specific scenario when the failure occurred (HP Spectre): When in category TIME and the user clicks on the back button, it will be first sent to category NUMBERS and after clicking the back button once more, a blank page occurs.
Another specific scenario: Click on „Go Back“ web application button when you open one of the folder except „Quick Chat“ > „Quick Chat“ folder always opens instead „Home board“
Another specific scenario: The user was in emotions submenu and after clicking the back button, it took the user to the time tab and then on the next click of back button to null page
(https://app.cboard.io/board/null) instead of redirecting to root or something.

* Expected result: The user returned to the home screen (or the screen the user previously has been on).

* Actual result: A blank page occurs, or other page other than home occurs when expected home page

**Comment by nathanbaleeta** [comment]
Attempts to reproduce this bug/ issue, show it no longer occurs on the cordova app, only occurs in certain computer browsers like firefox, but once the browser history is cleared, it ceased. So for now there is nothing much to fix, if it crops up again then we'll try to reproduce the steps and address it.
