### ISSUE TITLE
(Un)locking is not working properly after clicking Build option

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#547]
After playing with the Build option in the app, i.e. clicking Boards, Public boards etc., and going back to home screen, the app is locked after 3 clicks on the padlock and unlocked with 1 click.
I attached here a screenshot showing that 3 clicks are necessary to unlock the application but the application is already unlocked and after 3 clicks goes to being locked.
![Screenshot_20191108-113804_Cboard](https://user-images.githubusercontent.com/57595384/68547411-b789ae80-03e1-11ea-8dbb-cdf91ecc7c05.jpg)

**Comment by shayc** [comment]
Hi @mzilak , I tried to reproduce the issue on Windows laptop and couldn't, do you know if the problem still occurs?

**Comment by mzilak** [comment]
> Hi @mzilak , I tried to reproduce the issue on Windows laptop and couldn't, do you know if the problem still occurs?

Hi @shayc , it seems to me that this problem is fixed (in this particular scenario after "playing" with Build options for sure (on both, tablet and Windows laptop)).

**Comment by shayc** [comment]
@mzilak thank you! Closing this issue.
