### ISSUE TITLE
Wrong Montenegrin translation of Cboard

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#556]
Choose of Montenegrin language in the Settings of Cboard does not change the language to Montenegrin but English. Also, the English translation of symbols is imported and shown in the form of path from cboard.json file, e.g. symbol.foodFruit.apple.

**Comment by martinbedouret** [comment]
Thank you.
This is fixed on version 1.0.7 that I just released on Google Play Store , it will be available in few hours
