### ISSUE TITLE
White screen situations

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#559]
In 1.0.7 version of application, I came across white screens in several situations, some of them I suceeded to reproduce:
1) white screen occured when I changed the title (in some cases and color) of existing tile (default or the one I created)
2) white screen occured when I added a new board after I logged in
3) white screen occured when I hit the hardware back button while in All my boards option (after selecting some of my boards to be my home board and viewing all my boards)

In first two cases, I managed to go back to application after killing it from recent apps but in the 3rd case, I didn't. Also, after some time of using the application, I didn't manage to reproduce first two situations, I just noticed short white screen after changing the title of existing tiles.

**Comment by martinbedouret** [comment]
fixed on 1.0.11
