### ISSUE TITLE
'All my boards' option remembers not only 'boards'

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#561]
When choosing All my boards setting after using the app for some time, there can be found not only my boards but also folders I created as well as all the default folders where I made some change, e.g. edit a title of a tile. This option behaves almost like a 'history review'

**Comment by martinbedouret** [comment]
Great job as usual @mzilak !
This is the way it was designed. On Cboard a folder and a board are the same thing. Then, the all my boards option shows both things.
I could maybe explain better to the users that every time they create a folder they're creating a new board
