### ISSUE TITLE
All my boards available only when online and missing boards/symbols in offline mode

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#565]
When in option Build, Public boards and All my boards are available only if we are connected to the Internet which can be a problem for specialists working with users in the institutions where there is no Internet connection. 
This is especially important because some of our participants who are using Cboard (the latest version) complaint that they made boards at home with internet and then when they got to the institution, the board was missing. Also, they complaint about missing some symbols when they are in offline mode.

**Comment by martinbedouret** [comment]
Fixed
