### ISSUE TITLE
Complete development of SymbolDetails screen

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#57]
Complete UI of SymbolDetails screen, mainly CSS work and remaining bugs (adding folders)

**Comment by amberleyromo** [comment]
@shayc do you want help with this?

**Comment by shayc** [comment]
absolutely  :)

**Comment by amberleyromo** [comment]
Hey @shayc i did some just refactoring, want to make sure stylistically its in line -- check it out and comment over here: https://github.com/amberleyromo/cboard/pull/1

**Comment by shayc** [comment]
Closing to cleanup stale issues
