### ISSUE TITLE
Editing a tile from default folder causes white screen with loading icon

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#573]
After editing a title of a tile from the folder on a home board and after clicking Save button, the white screen with loading icon shows. At this point you can't go back but you have to go out from the application by killing its process and removing cache memory. 
Version application from 25th November

**Comment by mzilak** [comment]
Second time, I managed to click on a Save button but after clicking back button, it showed white screen with loading icon. Possible connection with bug #560

**Comment by martinbedouret** [comment]
fixed on 1.0.11
