### ISSUE TITLE
Choosing my board as home board in Build option doesn't work

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#576]
After choosing my board as home board in Build option (under Boards) and closing the application, I opened the application again and the default board was shown as home board - not the one I marked in the Build option.

**Comment by martinbedouret** [comment]
This is not actually a bug.
Cboard remembers the board that is displayed just before you close the app and then it shows the same board when you open it again.
The home board is actually used when you start a session. Hence it will be displayed if you logout and login , or starting a session on a different device.

**Comment by bppanwar** [comment]
In that case, the option to set the board as Home board in Builds option should be removed otherwise it creates confusion.
