### ISSUE TITLE
Implement Board removal

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#602]
The number of board is easily multiplied when starting using the tool. At the beginning, tests are usually done, and these board should be removable permanently from the boards database. 

Board removal should be available from:

- communicator builder , under "My Boards" tab

**Comment by remusonline** [comment]
Because of the permanent removal of the board from the database, strongly suggest to have a confirmation step (either popup or enter "delete" in a field) before proceeding with the deletion.

**Comment by remusonline** [comment]
Also, having the possibility to remove a board permanently from the database could lead to broken links. Either broken links should be managed somehow (404 page for the communicator), or an integrity check could be determined at the time of deletion to ensure that none other boards are linking to the board to remove (may be complex to manage, especially considering imports/exports).

**Comment by martinbedouret** [comment]
this has been added and merged
