### ISSUE TITLE
Linking between existing boards:

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#603]
Linking between existing boards: It seems that when creating a folder, the application does not link to an existing board when using the same name for the folder. This is especially useful when developing boards in advance, so that the communicator can evolve though time and user ability. I think I can circumvent this by exporting the .JSON, modify it and re-importing it in CBoard, but this is far from practical.

**Comment by remusonline** [comment]
Example of a Use Case:
![Use Case](https://user-images.githubusercontent.com/45130638/72026068-3c5d4100-3248-11ea-9ffc-44250eeb722c.png)
Having such a structure might be problematic, considering how the "back" button is implemented. If a memento pattern is used, this should not be a problem though.

**Comment by remusonline** [comment]
Quick Mock-up of how such link would be added:
![mockup](https://user-images.githubusercontent.com/45130638/72028019-17b89780-324f-11ea-864c-60e15409b1cf.png)

**Comment by Okelm** [comment]
When a user creates a new folder it seems that it becomes a board and a folder at the same time. I've created a new folder "New folder" and it is visible as an item in the board but also as a new board:
<img width="234" alt="Zrzut ekranu 2020-01-14 o 11 26 02" src="https://user-images.githubusercontent.com/14316935/72337161-5cff1e00-36c2-11ea-8666-63a24dd9da23.png">

@martinbedouret do you want to link that new folder to something else than to the "mother" board?

**Comment by martinbedouret** [comment]
Some contribution from EA Draffan (ead@ecs.soton.ac.uk) on this feature:

> Thank you so much and I have been experimenting with the new actions and they work well on my laptop with a Chrome Browser.  
> 
>  
> 
> However I think I am being very stupid as I cannot work out how to add the board I copied to my communicator as a board linked to a folder I have made.
> 
>  
> 
> For example a 'drink' folder and say I want to link it to the newly copied board called 'Cozinha' how can this be achieved? (see attached images)   
> 
>  
> 
> I realise a new folder automatically creates a new board, but there is no way of taking the copied tiles into that board or making a link or have I missed something?
> 
>  
> 
> Could there be a method for adding the copied board via the edit menu?   So when deciding whether to add a tile, folder, empty board there is also an option to add a copied board.  
> 
>

**Comment by martinbedouret** [comment]
After talking the Cboard architecture into account and incorporate the comments from @remusonline and @Okelm , it looks that a good solution here will be the capacity of link an existing board at the time to add a new folder into a board. This will cover all the possibilities:

- Buttton 
- Empty folder: will create an empty Board linked to the parent board.
- Linked folder: will create a link to an existing board into the parent board.
- Empty Board: will create an empty board without any kind of link.

![image](https://user-images.githubusercontent.com/8397930/73601790-5a1b7e80-4546-11ea-8ec3-5699b7d98794.png)

**Comment by remusonline** [comment]
Works beautifully! Thumbs up!

**Comment by martinbedouret** [comment]
Thank YOU ! This was your idea !
