### ISSUE TITLE
Option for hiding the sentence bar available through the settings menu.

### ISSUE THREAD

**Issue by remusonline** [cboard-org/cboard#608]
For younger users (starters), it may be easier to not have a sentence bar to concentrate on the pictograms. A retractable sentence bar could also be envisioned to give more real estate to the pictograms (particularly useful when using a phone).

Options for the sentence bar could be available through the settings menu.

**Comment by martinbedouret** [comment]
Absolutely agree with this.
Should be something simple to implement so I flagged it for help wanted.
