### ISSUE TITLE
Feature: Vocalizable folders

### ISSUE THREAD

**Issue by remusonline** [cboard-org/cboard#611]
An interesting function when navigating would be to have the folder spoken upon selection. This could prove particularly useful when implementing a digital version of PODD (Pragmatic Organization Dynamic Display), which should be possible once linking to existing boards feature is implemented.

**Comment by remusonline** [comment]
This can actually be accomplished by modifying the handleTileClick method in Board.container.js, at least for the sound playing part of the issue. The other part is to create a menu item to enable/disable the feature, and use this flag to play the sound of the tile or not depending on that selection.

**Comment by sylvansson** [comment]
I would love to tackle this issue. Is anyone else working on this already?

**Comment by martinbedouret** [comment]
It would be great @sylvansson !! 
It's all yours
Please don't hesitate to ask me anything you want. Thanks

**Comment by martinbedouret** [comment]
@remusonline and @sylvansson Cboard 1.3.0 was released with your design and implementation. Thank you guys for your wonderful collaboration !
Also available on the Android app on Google play store !

**Comment by remusonline** [comment]
Hi,

I tried it earlier, and it works perfectly. We are now only a few steps
away of supporting PODD with cboard. Thanks for the implementation
@sylvansson, I really appreciate it :-D.

Thanks!

Remusonline

**Comment by martinbedouret** [comment]
@remusonline fantastic. Could you please let me know what is left in order to fully support POOD?

**Comment by remusonline** [comment]
Sorry for the delay!

First of all, let's keep in mind that PODD is based on a physical medium i.e. dedicated book, so there is not really guidelines for a digital version of it. Obviously, the challenge to correctly support PODD, especially for beginners/young kids, is to provide expandability; at first, only a few board would be present. The number of boards and the re-organization of the board (links/folders) should evolve over time.

That being said, we currently have an issue with cboard regarding the removal of boards (I mentioned that issue in ticket #629). This issue needs to be resolved to correctly support the expandability of a digital PODD. At first glance, I have the feeling that deep architectural changes will be required, considering how boards and links are seen in the application. We should support an architecture where boards can be created and deleted independently, which doesn't seem to be the case right now.

Apart from that, we should also support "vocalizable sentences", which is the next step from the vocalizable folders. Essentially, we should include the folders into the sentence to be produced.

This is what I can think of right now to support a digital version of PODD. I must admit that I'm somewhat new to that concept, and I intend to research that more in the weeks to come. I may have other suggestions by then.

Thanks for your awesome work guys!

Remusonline
