### ISSUE TITLE
Walkthrough for new users

### ISSUE THREAD

**Issue by mcnuttandrew** [cboard-org/cboard#62]
Hey all, 
Congrats on the splendid project! I think y'all are doing really excellent work here. Poking around the app I found myself confused by how to access all of the functionality, and confused by what some of it does (eg, i'm very confused what the SELECT button does). I think this could be resolved pretty modestly by adding a walkthrough for first time users (as determined by a value held in localStorage or on the cookie). There are a ton of walkthrough libraries out there, such as react-joyride etc and it seems like they'd all do a great job here.

**Comment by shayc** [comment]
Thank you for the input, react-joyride seems interesting but we will only implement once things settle UI wise. I know @amberleyromo wants to have  take on UI, and we may need to block editing capabilities in 'user mode' vs 'speech therapist/edit mode' - welcome aboard!

somewhat related: #22

**Comment by martinbedouret** [comment]
hi @mcnuttandrew ,  we are really interesting in to implement something like this .
I think that the best way at this point is simply to add a new `live_help` button that shows a number of help callouts spread over the most important ui elements of the current screen .
See below mockup:

![image](https://user-images.githubusercontent.com/8397930/56097367-753ed400-5ec9-11e9-825e-9b8fb7b5bcd2.png)

**Comment by martinbedouret** [comment]
@mcnuttandrew here is the `live_help` button from material ui icons 
https://material.io/tools/icons/?icon=live_help&style=baseline

I don't know what would be a good reactjs component for this , but here there is one :

- https://github.com/Vishal1419/react-callout-component

**Comment by mcnuttandrew** [comment]
I'm glad this is getting some attention! It'll be great for new users. I am not going to be able to implement this, so it would be best to assign this someone else.

**Comment by martinbedouret** [comment]
No worries! Thanks for the heads up.
Assigned to @jtaco

**Comment by martinbedouret** [comment]
Assigned to @aljvilla

**Comment by ROHROCK** [comment]
Hi is anyone working on this ? I would like to contribute on this feature if its available . I found [react joyride](https://github.com/gilbarbara/react-joyride) which could help.

**Comment by martinbedouret** [comment]
@ROHROCK It's a great opportunity to know about you! 
Nobody's working on this so you can take it. Please let me know if you need anything!

**Comment by shayc** [comment]
@ROHROCK assuming you're not working on this anymore?

**Comment by katerinadimatou** [comment]
We want to undertake the walkthrough!

**Comment by mariaspastef** [comment]
We would really like to work on this!

**Comment by shayc** [comment]
Related article: [Practical Guide To Product Tours In React Apps](https://www.smashingmagazine.com/2020/08/guide-product-tours-react-apps/)
