### ISSUE TITLE
Context aware back button that looks like it should take a user to the top (first) board

### ISSUE THREAD

**Issue by eadraffan** [cboard-org/cboard#630]
I am just wondering if the context aware button that looks like a 'go to the first board'  should take the user back to the home board (top board) rather than just one back if one has three layers.  It has a line and arrow indicating the end of something or the beginning.  I have made some PowerPoint slides to illustrate the issue as this arrow could be helpful if there are three layers when linking folders. 
[Keeping links down to three layers.pptx](https://github.com/cboard-org/cboard/files/4203619/Keeping.links.down.to.three.layers.pptx)

**Comment by remusonline** [comment]
Makes sense, you want that button as a home shortcut, which would "de-stack" the boards (would be like if someone pressed a number of times the back button to get to the home board)

**Comment by eadraffan** [comment]
Yes that is right and instead of pressing twice in this case you go directly home to the top board.  This would allow a good AAC user to have several layers (to linkmore boards with a larger vocabulary), without repeated clicks back through each layer.
