### ISSUE TITLE
Allow exporting just a single board using the obf file format 

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#653]

**Comment by sylvansson** [comment]
@martinbedouret I see that we already have an option to export a single board in the Open Board Format, but in an OBZ file. Do I understand correctly that we want to be able to export to a single OBF file instead, with all images and sounds embedded directly in the file with the `data` property?

**Comment by martinbedouret** [comment]
@sylvansson an obz is a collection of obf files zipped into a single file. On Cboard when you export a board using open board format, you export all current boards into a single obz file. So then. Cboard code is first generating the obf's and then it zip the files in order to obtain an obz file.
The goal here is simply to allow the user to pick a board and to export the obf for that board.

https://www.openboardformat.org/

**Comment by sylvansson** [comment]
Got it, thanks. I should be done by the end of the week, and will reach out if I have questions.
