### ISSUE TITLE
Feature Request: add a second written language 

### ISSUE THREAD

**Issue by muescha** [cboard-org/cboard#66]
it would be nice to have a setting for a second written language displayed so it can also be used as a fast visual translator.

**Comment by shayc** [comment]
Thanks! Feature requests gets prioritized by the speech therapist needs.
What I was thinking with this feature: a quick toggle to switch between two chosen languages, like you have in your mobile keyboard if you're bi-lingual. Switching between languages will keep the `<Output/>` state (will need to be moved to Redux) allowing users to compose a sentence in two languages (if that makes sense).

**Comment by amberleyromo** [comment]
@muescha can you clarify what you mean? @shayc I read this feature differently -- like using it as a real-time spoken translation tool between two people speaking different languages. Like if I were to use it in English (as an English speaker) wanting it to vocalize speech in, say, German, to communicate with a German speaker. Have I totally misinterpreted?

I think we had talked several months ago about this as a potential application later down the road.

**Comment by muescha** [comment]
I expected in an Box

```
<image>
<description 1>
<description 2>
```

There is an new additional line `<description 2>` where I can set the description in a second language.

**Comment by muescha** [comment]
The voice can be also then in 2 languages ...

**Comment by shayc** [comment]
@martinbedouret should be prioritized against speech therapist

**Comment by shayc** [comment]
closing, lack of real world usage with our user base
