### ISSUE TITLE
Eliminate deprecation warnings (PropTypes, createClass)

### ISSUE THREAD

**Issue by amberleyromo** [cboard-org/cboard#68]
Deprecation warnings for propTypes and createClass

> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

> Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

Appears to be coming from [react-grid-layout](https://github.com/STRML/react-grid-layout/) module. [Related issue](https://github.com/STRML/react-grid-layout/issues/584) (PropTypes) in module repo.

**Comment by shayc** [comment]
Will make a PR
