### ISSUE TITLE
Implement prettier config

### ISSUE THREAD

**Issue by amberleyromo** [cboard-org/cboard#69]
https://github.com/prettier/prettier/releases/tag/1.6.0

**Comment by Magellol** [comment]
Hey 👋 

Would we want to add `prettier` bundled with `eslint` to report errors in the editor (We can also add a CI to enforce some formatting rules)? Or just having `prettier` to format without forcing anything from developers?

I can take care of any of those, just wondering what you guys would like to have as a setup.

**Comment by shayc** [comment]
Sorry for the late reply, it's the holiday season in Israel, so I'm not available as I wish to.
I've added prettier last night, it is enforced on commits.

Sorry if I've snagged this task!

I'm going to refactor the components soon and later start writing the tests for all components.
After that I'll release a roadmap so people can know the exciting features on the road.
