### ISSUE TITLE
When dark theme is on, the links that appear in the app are not visible because of the blue color

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#694]

**Comment by martinbedouret** [comment]
![Screenshot_20200429-201621_Cboard](https://user-images.githubusercontent.com/8397930/80712946-12ff4400-8ac9-11ea-8a78-b76665fa1b81.jpg)
![Screenshot_20200429-201614_Cboard](https://user-images.githubusercontent.com/8397930/80712960-198dbb80-8ac9-11ea-89f1-109b35178bda.jpg)

**Comment by sylvansson** [comment]
I can take this one.

**Comment by sylvansson** [comment]
Sorry for the delay @martinbedouret.

**Comment by shayc** [comment]
@sylvansson nothing to be sorry about, thank you for your involvement!
