### ISSUE TITLE
When dark theme is on, when the output bar is clicked, it highlights the bar with white color so the text below the symbols can’t be seen because the text is also in white color.

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#695]
When dark theme is on, when the output bar is clicked, it highlights the bar with white color so the text below the symbols can’t be seen because the text is also in white color (screenshot in the attachment). I don’t know if users track the symbols and the text while the speech for whole sentences is reproduced, so I don’t know how big of a problem this is.
![Screenshot_20200429-185724_Cboard](https://user-images.githubusercontent.com/8397930/80713530-ff081200-8ac9-11ea-926d-f5514293f0f0.jpg)

**Comment by sylvansson** [comment]
I can take this one. Highlighting in a dark grey, like where it says "RUKE", would probably do the trick. What do you think?
