### ISSUE TITLE
Simplify process for adding/updating translations

### ISSUE THREAD

**Issue by BrendanFDMoore** [cboard-org/cboard#70]
I'm working on setting up some scripts to help smooth for process of adding and modifying translation strings to Crowd In for approved contributors.

Right now the process is pretty clunky, and I think it can be a lot cleaner. I'm opening an issue just to  share that this is WIP to avoid duplicated effort.

**Comment by shayc** [comment]
[crowdin api](https://support.crowdin.com/api/api-integration-setup/)

**Comment by BrendanFDMoore** [comment]
First PR towards this goal is open #75
