### ISSUE TITLE
Export all boards into PDF exports just the board in view

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#706]
As the title says, export all boards into pdf isn't working as expected.

**Comment by martinbedouret** [comment]
This is not a bug, the user is advised in the message:
![image](https://user-images.githubusercontent.com/8397930/83767389-f8823280-a653-11ea-80e0-16c59c9bc6a2.png)
Exportation of a full dataset in PDF is having performance issues and hangs the application in most of the cases.

**Comment by shayc** [comment]
Then let's remove the option, if I got confused others will too.
We can keep the same option where it is relevant in "Export board"
