### ISSUE TITLE
Possible German vocalization setting bug

### ISSUE THREAD

**Issue by amberleyromo** [cboard-org/cboard#71]
Described in channel:

>  see a standing problem, though - the text-to-voice bot you have has zero idea how to pronounce German. There are totally different word stresses and different pronunciations for lots of letters in German, and it doesn't know those, or at all what to do with the umlauts ('ü' comes out like a v, for example, so über is said like 'veeber'). A lot of the words will be very difficult to understand for a German speaker.

This sounds like an issue with the voice setting.

**Comment by ioRekz** [comment]
I'm investigating the issue

**Comment by ioRekz** [comment]
The issue concern the translation page https://shayc.github.io/cboard-translate/ , the text to speech seems to always be set to English. 
I didn't look further.

**Comment by amberleyromo** [comment]
See #72
