### ISSUE TITLE
(Un)locking is not working properly after trying to change board title on web Cboard

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#711]
After trying to edit the board's title (#710 ), I noticed that toggle button for unlocking, when clicked, is showing the opposite information for how many clicks is needed for (un)locking.
The lock image is unlocked but it says there are more clicks needed to unlock the board (but actually it locks it and 1 click unlocks it).
(Lenovo laptop, Chrome browser)

![image](https://user-images.githubusercontent.com/57595384/84699357-a8f40e80-af51-11ea-9b8e-887fecddda80.png)

**Comment by martinbedouret** [comment]
@shayc I know you were working on this. Could you please take a look?

**Comment by mzilak** [comment]
This used to be an issue after going to Build option and returning to home screen, and after it was fixed in this situation, I didn't noticed it until now (after the board title isn't edited). This also happens on Android version (tablet Samsung Galaxy Tab A).

**Comment by shayc** [comment]
I’ll take a look

**Comment by sylvansson** [comment]
@shayc I'd be happy to work on this if you have more urgent tasks.

**Comment by sylvansson** [comment]
@martinbedouret I wasn't able to reproduce this.

**Comment by martinbedouret** [comment]
@sylvansson Yes, this is hard to reproduce. Let's keep it in the backlog for now.

**Comment by tomivm** [comment]
I could reproduce this. I get the same case described when I create an empty board. the actions to lock and unlock are switched. 
I'm working on this.
