### ISSUE TITLE
Settings > languages does not display all the available languages on windows/firefox

### ISSUE THREAD

**Issue by ioRekz** [cboard-org/cboard#72]
One user only had English.
I had English and French.
No error in the console
![language_setting](https://user-images.githubusercontent.com/688774/30070623-544d584e-9264-11e7-92e2-64ebeef57a76.png)

**Comment by shayc** [comment]
Can confirm: Windows 10 / Firefox.
Seems like Firefox on Windows only supports English in speechSyntesis.getVoices():

related: http://mdn.github.io/web-speech-api/speak-easy-synthesis/

Will check on Mac...

**Comment by ioRekz** [comment]
It works well for me on mac

**Comment by shayc** [comment]
same, I can only assume it doesn't come with speechSynthesis voices so it uses the platform's (windows/mac).

We need to verify this by adding another language to Windows, if both Edge/Firefox support the added language we can close this ticket.. will do it when I get some free time

**Comment by shayc** [comment]
can confirm: upon installing french language pack for windows 10, I have another option in Firefox.
Closing
