### ISSUE TITLE
Check the Cboard Android application to support all versions of OS

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#725]
Using Browserstack, we have to Check the Cboard Android application to support all versions from 6 to 10 inclusive. 
Please provide a table showing results for each device and OS tested.

**Comment by kidcompassion** [comment]
@martinbedouret I can do this, but does it matter if I use [LambdaTest](https://www.lambdatest.com/) instead of Browserstack?

**Comment by kidcompassion** [comment]
@martinbedouret disregard! I can't, my tier of Lambdatest doesn't allow for mobile testing. 🤦‍♀️

**Comment by martinbedouret** [comment]
@kidcompassion I can grant you full access to our instance in Browserstack, we have an enterprise account there and you can test in a wide range of devices and OSs. Just let me know the email address you would like to receive the invite.

**Comment by kidcompassion** [comment]
@martinbedouret Awesome, thank you! I just DM'd you info in Discord.

**Comment by martinbedouret** [comment]
all done
thank you !

**Comment by kidcompassion** [comment]
@martinbedouret I'm so sorry I left this hanging, but thank you for your patience! I have started this now and will continue to work on it over the coming days/weeks.

Doc of user stories/testing so far can be seen [here](https://docs.google.com/spreadsheets/d/1kfOYTK8lD31Fym5zd1YkYxiarl2wjs3xwmWGpVU7QkE/edit?usp=sharing), and I'm tracking issues [here](https://app.milanote.com/1Kjke31TVUK5dZ?p=3XZtz0aKVNX) for now. 

Once I get through multiple versions, I'll go back, retest any bugs to capture more detail, then add them into GitHub as issues.

**Comment by tomivm** [comment]
I do the Checks using BrowserStack and V 1.9.1 of Cboard APP. 
A common problem was on a moment to select tiles for edit. was no good reaction with clicks. I used the keys tab - enter and work properly. I think this is a problem with BrowserStack. I should confirm.
there is a bug that Cordova doesn't detect logged users on shareBoard Dialog. i will create an issue.
[Cboard Android Support v1.9.1 - 25-05-2021.pdf](https://github.com/cboard-org/cboard/files/6517097/Cboard.Android.Support.v1.9.1.-.25-05-2021.pdf)
please if the table is required in another format let me know!
