### ISSUE TITLE
Searching symbols from Global Symbols finds the symbols but without the picture

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#733]
In edit mode, while searching for new symbol from Global Symbols, the symbols can be found but without the picture.
In the screenshots you can see I searched for "ti" symbol, and that this symbol exists in the symbol set from Croatia "Hrvatski simboli za PK": 
![Screenshot_20200627-102023_Cboard](https://user-images.githubusercontent.com/57595384/85920163-b8d4f200-b871-11ea-922c-0a39d68af543.jpg)
![Screenshot_20200627-102110_Chrome](https://user-images.githubusercontent.com/57595384/85920164-ba061f00-b871-11ea-9a89-1c0577e4a42d.jpg)

**Comment by martinbedouret** [comment]
@mzilak that looks like an internet connection issue. I just tried the same and got the images successfully. Do you agree to close this?

![image](https://user-images.githubusercontent.com/8397930/86809847-aff2d600-c052-11ea-9370-6886671eb295.png)

**Comment by mzilak** [comment]
@martinbedouret , I am sure that I had internet at the time, probably this was only temporary as a result of interventions on Global Symbols site. Everything is ok now so I agree to close this.
