### ISSUE TITLE
Editing folder label changes the label only on a tile on a board but when you enter the folder, the old label is shown

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#735]
Editing folder label changes the label only on board but when you enter the folder, the old label is shown (and while you are not logged in, you cannot change the name of the boards/folders).

**Comment by martinbedouret** [comment]
Good catch Matea!

**Comment by sylvansson** [comment]
In this context, we are renaming the folder itself, so I find it reasonable not to rename the linked board automatically. Perhaps we could let the user choose between renaming both or just the folder. @mzilak Would you also want folders to be renamed automatically when you rename a board?

**Comment by mzilak** [comment]
@sylvansson, since there is also an option in the settings to turn on the vocalization of the folder when it is clicked, I think it would be strange to hear title od the folder which is different then the title of the board. Also, some folder has symbols related to communication in some specific activities, related to certain place, play, food etc. It is not likely to have the same folder renamed in many possible titles. If it will be used in a different context, a new folder will be created. What would help here is to have the option to duplicate the folder

**Comment by mzilak** [comment]
@martinbedouret , if you could please tag EA here to comment on this if I'm not right. I tried but could not tag @eadraffan

**Comment by eadraffan** [comment]
Many thanks Martin and Matea.  I have found I can make boards with the same title name but with different numbers of tiles which means I have to be very careful when I want to link to them from another board. If I am understanding you, we would need to make sure the folder title changes but then this would affect the vocalisation and understanding for the child who needs the same label and symbol for the category concept to be learnt.  So I am not sure how you can get round this issue unless there is a separate title for the folder board from the symbol label that needs to be vocalised.   I am wondering if I am now muddling things - so sorry if this is the case :>((

**Comment by mzilak** [comment]
@eadraffan , since you are the expert, you know better what is it that expert users will want:
1) When folder title is edited, does this need to affect the board/folder title when you enter it? OR
2) When folder title is edited, does the board/folder title when you enter it remains the same? In this case, when you rename the folder, does this become a new board you can access from board menu or it doesn't have to? OR
3) When folder title is edited, we ask a user to choose between renaming both, folder and board, or just the folder?
4) When in board and the title is changed, does this affects all folder titles that this board is linked to?

**Comment by eadraffan** [comment]
No way - not an expert in anything!  I just think to get this right we both need to have our tablets on with Cboard and talk through the actions as I am finding this hard to untangle without thinking through the ramifications in all situations!  It would also be good to have a decision tree so that Martin can see our thinking and anyone else who wants to join us!!  In other words I am worried that unless we discuss it carefully we will restrict others down the line to something that affects multiple folder creation and duplications for multiple different boards and the impact on the linked boards which is an issue you rightly raise!

**Comment by martinbedouret** [comment]
I'm closing this. From my perspective, the current implementation is the most conservative approach and it just doesn't hurt since it doesn't make hidden updates. So if you're changing the title of a board, the change will update JUST the title of the board and NOT TITLE and FOLDER.
