### ISSUE TITLE
TIFF images are lost when importing a single board using Cboard format (json)

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#764]
1. Import the attached board, it contains cloud images on the major formats.
2. Check the board on the Cboard ui
3. TIFF Image is lost

[images formats board.zip](https://github.com/cboard-org/cboard/files/5013171/images.formats.board.zip)

**Comment by sylvansson** [comment]
It looks like the image isn't actually "lost", however most browsers [do not support](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support) embedding a TIFF image natively. One solution would be to handle this format differently by converting the image to a data URI, or we could simply not support TIFF files altogether. What do you think @martinbedouret?

**Comment by martinbedouret** [comment]
@sylvansson great job doing research. Let's simply not support TIFF files.
