### ISSUE TITLE
About Language & contribution

### ISSUE THREAD

**Issue by btk** [cboard-org/cboard#79]
Hey @shayc, great work! 

We analysed this app at Otsimo in office and really loved it. We made this aac app; https://github.com/otsimo/aac 

After I leave Otsimo, I started working on another version and flow of AAC app (also better in performance) in my free time I would like you to check it;
https://github.com/btk/aac-native

Addition to that, I saw that this project generates its language data with translator, for example in Turkish version of it, there is problems that people in the spectrum might get effected.

In my project, we use a plain json file to store the locale data and its easier to edit. I created an issue in the project with label Hacktoberfest and asked people to translate the file into their native language. 
https://github.com/btk/aac-native/issues/2

In just 3 days, I saw great results. People like to contribute to get Hacktoberfest credits, also the language translation would get more accurate. 

You might want to do something like this for this project. As I see you also store the data in json file. If you create a flow for people to pull request their changes or corrections instead crowdin.com, I think you will get results.

Also I personally did a lot of UX research about AAC apps if you have any questions, you can email me. Thank you.

**Comment by shayc** [comment]
hi @btk, thanks for making a contact!

I didn't manage to run either projects, I'll try soon again on the Mac. It seems we're practically working on the same projects, we should collaborate somehow, it'll be cool to talk with you on Skype, let me know, you can join our [Discord](https://discord.gg/TEH8uxh) channel and we'll take it from there.. would love to hear your thoughts.

Shay

**Comment by shayc** [comment]
Hacktoberfest tagging was a great tip! thank you so much for this!
