### ISSUE TITLE
Symbols do not show when board is in fixed mode

### ISSUE THREAD

**Issue by AlexDoggo** [cboard-org/cboard#853]
![F5978315-899D-4677-8DEE-2E5C4629E72F](https://user-images.githubusercontent.com/33941250/109531862-10210700-7a7e-11eb-84e8-78bf89dcb044.png)
![81790F88-6974-4938-9307-D2FB17E564FE](https://user-images.githubusercontent.com/33941250/109531881-14e5bb00-7a7e-11eb-81cf-d98e13f9395b.png)

**Comment by shayc** [comment]
Bug only reproduces on iOS devices (iPhone/iPad), perhaps also on Mac Safari (need to verify).

Related to CSS Flex height not being calculated.

**Comment by hectoritr** [comment]
I can confirm that it is not showing on Safari without sign-in.
<img width="1440" alt="Captura de Pantalla 2021-09-07 a la(s) 12 20 06" src="https://user-images.githubusercontent.com/12820318/132370453-8a097d02-b0aa-4acd-a69e-5455ad399a20.png">

**Comment by hectoritr** [comment]
But when I sign in it works both fullscreen and resized.

<img width="1440" alt="Captura de Pantalla 2021-09-07 a la(s) 12 37 58" src="https://user-images.githubusercontent.com/12820318/132372999-a7cd8f05-f53c-46bb-a426-311f0d895b11.png">
<img width="1440" alt="Captura de Pantalla 2021-09-07 a la(s) 12 37 37" src="https://user-images.githubusercontent.com/12820318/132373024-1ffb9e28-7b23-4e28-9341-5bf6f2807017.png">

**Comment by tomivm** [comment]
@hectoritr It's not related to the login. the problem is when the board and tiles are fixed. thanks for your help!
