### ISSUE TITLE
Make current phrase shareable

### ISSUE THREAD

**Issue by thoka** [cboard-org/cboard#861]
I would like to be able to  share the current phrase,  for example to send it via email or copy it into a word processor.

I could imagine multiple ways to support this:
- copy to clipboard by  ctrl+c
- add a copy to clipboard symbol next to "clear" and "delete"
- support dragging of the phrase to some other programm
- add a "share" button to select further options (at best user configurable providers)

**Comment by shayc** [comment]
@thoka great suggestion, how do you imagine the output? Just text or with symbols?
@martinbedouret what do you think? We need to keep the UI simple for the end-user, so "Copy to Clipboard" button will be opt-in from the settings.

**Comment by thoka** [comment]
> @thoka great suggestion, how do you imagine the output? Just text or with symbols?

It would be great to be able to have text and text and symbols. 
The application could add text with symbols as html and only text as plain text into the clipboard.

**Comment by martinbedouret** [comment]
@tomivm assigned.
This was partially implemented on #880 .We have to transform the copy phrase button into a share phrase button. See below: 

![image](https://user-images.githubusercontent.com/8397930/117027289-f34dbd80-acd2-11eb-87e6-e03386d84180.png)

The share phrase button must share the text of the phrase. Also we have to update the text in the settings: 

![image](https://user-images.githubusercontent.com/8397930/117028027-acac9300-acd3-11eb-9aa4-357a93479cc6.png)
