### ISSUE TITLE
Cordova - implement login with Facebook and Google 

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard#862]
If you use the Google or Facebook login on the browser is not possible to open the same user and boards on the mobile app.
![image](https://user-images.githubusercontent.com/21298844/110726856-ee9bea00-81f8-11eb-9c91-032911ca7589.png)

**Comment by shayc** [comment]
@tomivm can you explain a little more? what browser/device?

**Comment by tomivm** [comment]
Yes of course. suppose the case that I'm a web app user and I commonly use the Google or Facebook sing up. if I want to use the app on android I will need to create a new one. the same to windows app. 
  I mean this is a issue to ccboard repository.
  I don't remember that device but here is a new screenshot with a Samsung S10.
![image](https://user-images.githubusercontent.com/21298844/112921554-5c914e00-90e1-11eb-8432-e64557e52001.png)

![image](https://user-images.githubusercontent.com/21298844/112921307-eab90480-90e0-11eb-8900-f80be7911099.png)
