### ISSUE TITLE
Refactor: Split component & container

### ISSUE THREAD

**Issue by BrendanFDMoore** [cboard-org/cboard#87]
This is an omnibus issue to track conversion for major components to split the stateless UI `component` from the redux-connect `container`.

To Do:

- [x] Board
- [x] Settings
- [x] Settings: Language
- [ ] Settings: Speech
- [x] Settings: Backup
- [ ] Notification
- [ ] Header
- [ ] Grid
- [ ] ...more?

**Comment by BrendanFDMoore** [comment]
@shayc is doing `Board` and I'm working on `Settings` for now.

**Comment by BrendanFDMoore** [comment]
Now working on the sub-modules of `Settings`: Language, Speech, Backup

**Comment by shayc** [comment]
Added basic container/component separation for `Board` module, marking as done for this dev phase
