### ISSUE TITLE
Cannot rotate the photo after I create a custom pane with my own photo

### ISSUE THREAD

**Issue by hanzhaogang** [cboard-org/cboard#881]
iphone ios 14.4 safira browser.

**Comment by shayc** [comment]
I assume you want to rotate an image after you upload it? If so I'm marking this as a feature request and not a bug since we don't have a capability to rotate images as of now.

**Comment by hanzhaogang** [comment]
> I assume you want to rotate an image after you upload it? If so I'm marking this as a feature request and not a bug since we don't have a capability to rotate images as of now.

Yes， that's right， a new feature.
