### ISSUE TITLE
After I define a custom tile with my own picture in my iphone, the tile cannot be found in the browser in my laptop.

### ISSUE THREAD

**Issue by hanzhaogang** [cboard-org/cboard#882]
windows 10 , microsoft edge.

**Comment by shayc** [comment]
@hanzhaogang when you say pane, I guess you mean a tile with an image?

**Comment by hanzhaogang** [comment]
> @hanzhaogang when you say pane, I guess you mean a tile with an image?

That is right, I upload a custom photo with my iphone, and cannot find it in my laptop brower.

**Comment by martinbedouret** [comment]
I have reproduced this with the following steps: 

1. Open a board in two different browsers (or devices )
2. browser A: Edit a tile to upload a local image and save 
3. refresh the browser B
4. New image is not displayed in browser B
5. refresh the browser B once again 
6. New image is displayed in browser B
