### ISSUE TITLE
Integrate with Global Symbols

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#90]
We want to integrate with [Global Symbols](https://globalsymbols.com/en/home/) - a symbol set for the Arabic community.

In the application a user should be able to search (and use) the new symbol set. The symbols should appear when a user searches for a symbol in the 'Add new button' menu.

This is the Tawasol API:

http://madaportal.org/tawasol/en/api-documentation/

The final goal is to display Arabic symbols from Tawasol API in case that the current language is an Arabic language. 

Implementation steps
-------

- check if current language is an arabic language when user tries to add a new folder or pictogram
- if arabic language is detected, search for symbols must include a call to the Tawasol API.
- Response from Tawasol *must be filtered* in order to display just the symbols from `"source_id": "1"`
- Tawasol results must be displayed in *First Place*

below an example of the final results:

![image](https://user-images.githubusercontent.com/8397930/55729639-e293c600-59ec-11e9-906a-e0b47428291b.png)

**Comment by martinbedouret** [comment]
This is ongoing.

**Comment by martinbedouret** [comment]
This was implemented.
