### ISSUE TITLE
Share sentence function needs a try/catch

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#901]
File: `Output.container.js`
Function: `handleCopyClick`

1) Need to wrap the code with a try/catch block since not all browser support `navigator.clipboard.writeText` and besides we want to be a little more defensive in our coding style.
2) Needs to add a new translation message for the "Failed to copy" string

Example:
```js
    try {
      await navigator.clipboard.writeText(labels.join(' '));
      showNotification(intl.formatMessage(messages.copyMessage));
    } catch (err) {
      showNotification(
        `${intl.formatMessage(messages.failedToCopy)}: ${err.message}`
      );
    }
```

**Comment by katerinadimatou** [comment]
We are interested in taking on this bug!

**Comment by shayc** [comment]
Assigned to the lucky winner @katerinadimatou :)

**Comment by mariaspastef** [comment]
I can work on it with Katerina

**Comment by katerinadimatou** [comment]
We believe we successfully fixed it! @shayc @martinbedouret @sylvansson

**Comment by sylvansson** [comment]
Great job @katerinadimatou @mariaspastef. I will take a look at your pull request later today :-)

**Comment by katerinadimatou** [comment]
Thank you so much! @sylvansson
