### ISSUE TITLE
Add Shareable current phrase to the user help

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#999]
We have to update the details of the user help file in order to include Shareable current phrase feature. This is the file: https://github.com/cboard-org/cboard-io/blob/master/_i18n/en/help/help.md

**Comment by tomivm** [comment]
linked PR: https://github.com/cboard-org/cboard-io/pull/53

**Comment by tomivm** [comment]
closed on https://github.com/cboard-org/cboard-io/pull/53
